### ISSUE TITLE
Compile dynamic library on the windows platform

### ISSUE THREAD

**Issue by gliwka** [intel/hyperscan#105]
I'm using hyperscan in my java projects and have developed java language bindings using JNA ([hyperscan-java](https://github.com/LocateTech/hyperscan-java)). 

My current goal is to add windows support. JNA relies on dynamic libraries, but the CMAKE build script only creates a static library on windows.

Is this due to the missing dll export declarations which windows demands (something that potentially could be at least partially solved using [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html#prop_tgt:WINDOWS_EXPORT_ALL_SYMBOLS) or creating a .DEF file). Ore are there other technical reasons for that?

**Comment by gliwka** [comment]
WINDOWS_EXPORT_ALL_SYMBOLS doesn't work, because it's just too many symbols.

```
LINK : C:\Users\mg\Desktop\Code\hyperscan-master\build\bin\hs.dll not found or not built by the last incremental link; performing full link
LINK : fatal error LNK1189: library limit of 65535 objects exceeded [C:\Users\mg\Desktop\Code\hyperscan-master\build\hs_shared.vcxproj]
```

Seems like a manual definition of the symbols to export is necessary. I'll try that next.

**Comment by wurp** [comment]
Hi Matthias, did you have any luck building hs.dll? I'm running into some initialization issues with Hyperscan that I believe a DLL would solve.

**Comment by gliwka** [comment]
Obsolete. Version 5.2.1 introduces windows dll support.
