### ISSUE TITLE
请问hyperscan支持括号提取子串信息吗？

### ISSUE THREAD

**Issue by ouliuquan** [intel/hyperscan#112]
类似于boost regex 的提取括号内符合正则表达式的子串，翻遍了所有的文档没有发现这个接口或者实例。

**Comment by xiangwang1** [comment]
We don't support capturing as it is not mandatory in many use cases and it also poses significant overhead to the performance. Please try Chimera if you real need this feature.

**Comment by ouliuquan** [comment]
Thank you.
