### ISSUE TITLE
C linux application using hyperscan lib crash at hs_scan() function

### ISSUE THREAD

**Issue by sambk** [intel/hyperscan#119]
Hi all,
I'm developing a C linux application using hyperscan lib to scan data. Normally, everything works fine but today i have a problem: The application crashes and the backtrace of core file is as follow:

> (gdb) f 0
> #0  0x0000000000977a18 in avx2_hs_scan ()
> (gdb) f 1
> #1  0x00000000004f9570 in run_dpi_scan (buffer=<optimized out>, size=<optimized out>, db_param=db_param@entry=0x8cc54f0 <apple_cfg+127952272>, ctx=ctx@entry=0x0,
>      m_scratch=<optimized out>) at /home/project/source/scanning.c:165
> 165        hs_error_t ret = hs_scan(db_param->db, buffer, size, 0, m_scratch, onMatch, ctx);
> (gdb)

It seems that the problem happens inside hyperscan library. Could anyone give me some advice how to solve it?

**Comment by delins** [comment]
Perhaps this information alone is meaningful to the developers, but my guess is it isn't. People might be better able to help you if you provide the code that deals with creating the parameters for the `hs_scan` call. Also, what changed between normally and now? Does it always crash or just sometimes? Can you reproduce the crash?

**Comment by sambk** [comment]
> Perhaps this information alone is meaningful to the developers, but my guess is it isn't. People might be better able to help you if you provide the code that deals with creating the parameters for the `hs_scan` call. Also, what changed between normally and now? Does it always crash or just sometimes? Can you reproduce the crash?

Thank Delins. Unfortunately, I cannot reproduce the crash, it happens very rarely, this has been the first time for many months. 

**By the way, could anyone with experience tell me what cases might make crash at the function hs_scan()?**

**Comment by sambk** [comment]
I solved it. It is my own bug that accidentally free hyperscan database. I close the issue now
