### ISSUE TITLE
fix `git clone git://github/intel/hyperscan` in dev-reference

### ISSUE THREAD

**Issue by nasciiboy** [intel/hyperscan#123]
`git clone git://github/intel/hyperscan` => `git clone git://github.com/intel/hyperscan`

https://github.com/intel/hyperscan/blob/gh-pages/dev-reference/getting_started.html line number 50

**Comment by xiangwang1** [comment]
Thanks nasciiboy, we'll fix it in the coming release.

Thanks,
Xiang

**Comment by xiangwang1** [comment]
Already fixed.
