### ISSUE TITLE
All the dependencys are ok, but hs compile error

### ISSUE THREAD

**Issue by wangfenggao** [intel/hyperscan#127]
root@xxx-xxxx-xxx:/home/xxx/git/hyperscan/build# cmake -DBUILD_STATIC_AND_SHARED=on ../
-- Build type RELWITHDEBINFO
-- Boost version: 1.60.0
-- Build date: 2018-12-25
-- Building shared libraries
-- gcc version 7.3.0
-- g++ version 5.4.0
-- generator is Unix Makefiles
-- Building runtime for multiple microarchitectures
-- Doxygen not found, unable to generate API reference
-- Sphinx not found, unable to generate developer reference
-- PCRE version 8.41
-- Checking for module 'sqlite3'
--   No package 'sqlite3' found
-- looking for sqlite3 in source tree
--   no sqlite3 in source tree
-- sqlite3 not found, not building hsbench
-- Could not find libpcap - some examples will not be built
-- Configuring done
CMake Warning (dev) at tools/hscollider/CMakeLists.txt:67 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "pcre" of target "hscollider" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/wfg/git/hyperscan/build

**Comment by xiangwang1** [comment]
Please remove this line to avoid the error: https://github.com/intel/hyperscan/blob/2060dd3a9cbce95a7c3cee8950c9ab0fb6024748/tools/hscollider/CMakeLists.txt#L67

We'll fix it in the next release.

Thanks,
Xiang

**Comment by wangfenggao** [comment]
Thanks a lot

**Comment by xiangwang1** [comment]
Fixed.
