### ISSUE TITLE
building with gcc 9

### ISSUE THREAD

**Issue by jmtaylor90** [intel/hyperscan#136]
In building the package for Fedora 30, which uses GCC 9, I ran into an issue that with assistance we were able to patch around for now.

Snippet from the build system log:
-- Boost version: 1.69.0
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Build date: 2019-02-12
-- Building shared libraries
-- gcc version 9.0.1
BUILDSTDERR: CMake Error at CMakeLists.txt:204 (message):
BUILDSTDERR:   Something went wrong determining gcc tune: -mtune=option: not valid
-- g++ version 9.0.1
-- Looking for include file unistd.h

patch:
https://src.fedoraproject.org/rpms/hyperscan/c/3e496494352a8c3b019ab0f17689b6e633cde559?branch=master

Let me know if any additional information is needed or I can help test a fix.

**Comment by xiangwang1** [comment]
Looks like the option to -mtune is not correct.
Could you provide the output of `gcc -c -Q --help=target -march=native -mtune=native` on your system and check the line that contains `-march=`?

**Comment by jmtaylor90** [comment]
So with gcc 9 it looks like the `gcc -c -Q --help=target -march=native -mtune=native` command has additional output from gcc 8. This additional output appears to be what is causing the problem.

snippet of `gcc -c -Q --help=target -march=native -mtune=native` on gcc 9 box: 

  Known TLS dialects (for use with the -mtls-dialect= option):
    gnu gnu2

  Known valid arguments for -march= option:
    i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native

  Known valid arguments for -mtune= option:
    generic i386 i486 pentium lakemont pentiumpro pentium4 nocona core2 nehalem sandybridge haswell bonnell silvermont goldmont goldmont-plus tremont knl knm skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake intel geode k6 athlon k8 amdfam10 bdver1 bdver2 bdver3 bdver4 btver1 btver2 znver1 znver2

If I mock up the regex used in CMakeLists.txt (line 194) on the gcc 9 box:
[jason@localhost ~]$ gcc -c -Q --help=target -march=native -mtune=native | grep -E ".*march=[ \t]*([^ \n]*)[ \n].*"
  -march=                     		ivybridge
  Known valid arguments for -march= option:

The same run on a gcc 8 box:
[jason@dinosaur ~]$ gcc -c -Q --help=target -march=native -mtune=native | grep -E ".*march=[ \t]*([^ \n]*)[ \n].*"
  -march=                     		ivybridge

It looks like REGEX_REPLACE will match as many times as it can and does not support {} matching to limit the number of matches.

**Comment by xiangwang1** [comment]
Looks like we need to get rid of valid arguments section before doing REGEX_REPLACE.

Will adding `string(FIND "${_GCC_OUTPUT}" "Known" POS)` and `string(SUBSTRING "${_GCC_OUTPUT}" 0 ${POS} _GCC_OUTPUT)` before `string(REGEX REPLACE ".*march=[ \t]*([^ \n]*)[ \n].*" "\\1" GNUCC_ARCH "${_GCC_OUTPUT}")` in CMakeLists.txt help?

**Comment by jmtaylor90** [comment]
Yes that works. Would you like a PR or do you already have one done?

**Comment by xiangwang1** [comment]
That's good. I'll prepare a patch to fix this issue.

**Comment by jmtaylor90** [comment]
Great, thank you!

**Comment by xiangwang1** [comment]
Fixed in master.
