### ISSUE TITLE
build failed when source path has `*.o` suffix

### ISSUE THREAD

**Issue by AirbornWdd** [intel/hyperscan#137]
There is a bug in the [build_wrapper.sh](https://github.com/intel/hyperscan/blob/master/cmake/build_wrapper.sh#L12) script. When I build the source code with path like '/home/blabla`.o`/hyperscan/', then shell command `OUT=$(echo "$@" | sed 's/.* -o \(.*\.o\).*/\1/')` in the `build_wrapper.sh` script will not get the expected result.

**Comment by xiangwang1** [comment]
Thanks for reporting this issue.
Will change `OUT=$(echo "$@" | sed 's/.* -o \(.*\.o\).*/\1/')` to `OUT=$(echo "$@" | rev | cut -d ' ' -f 2- | rev | sed 's/.* -o \(.*\.o\).*/\1/')` fix this issue?

**Comment by AirbornWdd** [comment]
> Thanks for reporting this issue.
> Will change `OUT=$(echo "$@" | sed 's/.* -o \(.*\.o\).*/\1/')` to `OUT=$(echo "$@" | rev | cut -d ' ' -f 2- | rev | sed 's/.* -o \(.*\.o\).*/\1/')` fix this issue?

YES. Thanks a lot ! 👍
