### ISSUE TITLE
NSDI 2019 paper about Hyperscan

### ISSUE THREAD

**Issue by zherczeg** [intel/hyperscan#138]
I saw a paper titled "Hyperscan: A Fast Multi-pattern Regex Matcher  for Modern CPUs" by "Xiang Wang, Yang Hong, and Harry Chang, Intel; KyoungSoo Park, KAIST; Geoff Langdale, branchfree.org; Jiayu Hu and Heqing Zhu, Intel". In the paper there was a comparison about PCRE2 and Hyperscan with JIT enabled. May I ask why the paper about PCRE2-JIT ("Extending the PCRE Library with Static Backtracking Based Just-in-Time Compilation Support" by "Zoltán Herczeg") was not cited?

**Comment by xiangwang1** [comment]
At the time of writing and doing evaluation for this paper, we referred to https://www.pcre.org/ for all PCRE related information. But I think it'll be good to include your paper.

**Comment by xiangwang1** [comment]
Close as this is not a project related issue.
