### ISSUE TITLE
windows系统编译示例显示collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped

### ISSUE THREAD

**Issue by hill123** [intel/hyperscan#140]
你好，我按照hyperscan on windows的步骤将代码编译，得到build/lib目录下有hs.lib等文件。
我试图在cygwin64上编译并运行simplegrep.c，生成了一个0KB大小的simplegrep.exe，并且命令行一直在执行没有停止，很久之后提示错误信息：
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file

**Comment by xiangwang1** [comment]
Hi,

Can you provide the compile command and your Windows environment (OS version, compiler, etc)?

Thanks,
Xiang

**Comment by hill123** [comment]
感谢您的回复，我使用的是windows8.1，gcc7.4.0，
在cygwin64执行命令是 gcc simplegrep.c -o simplegrep -I ~/hyperscan/src -L ~/hyperscan/build/lib -lhs -lstdc++ -lm
后来我又试着用vs2017引入头文件和lib库，编译成功了。

**Comment by xiangwang1** [comment]
That's great. We need to use VS compiler in Windows.
