### ISSUE TITLE
[FR] Compilation canceling

### ISSUE THREAD

**Issue by PlushBeaver** [intel/hyperscan#142]
Hello.

Databases of large size or with complex patterns may take considerable time to compile.  This presents DoS attack vector if such pattern sets are user input in multi-user systems, because of CPU exhaustion.  Mitigation by limiting pattern set size is a shrewd approach, neither does it protect against complex patterns.  Interrupting a compilation thread almost certainly causes memory leaks.

Related: https://github.com/intel/hyperscan/issues/90

Is there a plan or possibility to support cancellation in Hyperscan?  One may think about cancellation points inside implementation. API usage might be as follows:

``` cpp
// Decides whether to cancel compilation
int
should_cancel(void* userdata) {
    const auto start = reinterpret_cast<Timestamp>(userdata);
    if (now() - start > limit) {
        return HS_CANCEL;
    }
    return HS_CONTINUE;
}

// Setup thread-local cancellation callback
const auto start = now();
hs_cancellation_callback(should_cancel, (void*)start);

// During compilation, should_cancel() is called back multiple times
const auto result = hs_compile(...);

if (result == HS_CANCEL) {
    // Compilation timed out
}
```

**Comment by xiangwang1** [comment]
Hi,

Thanks for the questions. 
The problem with inserting cancel callbacks is that there are no obvious points to place them in the compile implementation. Hyperscan has a complex compile process with multiple stages and tons of optimizations. Any of the stages or optimizations could consume some amount of time depending on pattern characteristics. So cancel callbacks may mitigate this issue but can't completely address it. On the other hand, it also complicates the compile code.

We suggest external user handling if this is an issue.

**Comment by PlushBeaver** [comment]
Thanks for clarification, Xiang.
