### ISSUE TITLE
Chimera Release build mode lots of undefined reference error

### ISSUE THREAD

**Issue by JackLiar** [intel/hyperscan#153]
hyperscan version: 5.1.1&5.1.0&5.00
boost version: 1.57&1.70
pcre version: 8.41
Ragel version: 6.9
cmake version: 3.14.2 & 3.12.1

os version: CentOS 7.3.1611
gcc version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**I still get this error using Relwithdebinfo mode.**

gcc error:

```
../lib/libchimera.a(ch_compile.cpp.o): In function `ch::ch_compile_multi_int(char const* const*, unsigned int const*, unsigned int const*, unsigned int, unsigned int, unsigned long, unsigned long, hs_platform_info const*, ch_database**)':
ch_compile.cpp:(.text+0xbf1): undefined reference to `ue2::mmbit_size(unsigned int)'
ch_compile.cpp:(.text+0x1034): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x1050): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x1055): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x119a): undefined reference to `ue2::CompileError::CompileError(unsigned int, std::string const&)'
ch_compile.cpp:(.text+0x119f): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x11a4): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x12b8): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x12d4): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x12d9): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x1320): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x133c): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x1341): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x13e8): undefined reference to `ue2::CompileError::CompileError(unsigned int, std::string const&)'
ch_compile.cpp:(.text+0x13ed): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x13f2): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x1450): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x146c): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x1471): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x14ad): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x14c9): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x14ce): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x150a): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x1526): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x152b): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x1760): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x177c): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x1781): undefined reference to `typeinfo for ue2::CompileError'
ch_compile.cpp:(.text+0x17ce): undefined reference to `ue2::CompileError::CompileError(std::string const&)'
ch_compile.cpp:(.text+0x17ea): undefined reference to `ue2::CompileError::~CompileError()'
ch_compile.cpp:(.text+0x17ef): undefined reference to `typeinfo for ue2::CompileError'
../lib/libchimera.a(ch_compile.cpp.o):(.gcc_except_table+0x180): undefined reference to `typeinfo for ue2::CompileError'
../lib/libchimera.a(ch_compile.cpp.o):(.gcc_except_table+0x1d8): undefined reference to `typeinfo for ue2::CompileError'
../lib/libchimera.a(ch_compile.cpp.o):(.gcc_except_table+0x230): undefined reference to `typeinfo for ue2::CompileError'
../lib/libchimera.a(ch_runtime.c.o): In function `multiCallback':
ch_runtime.c:(.text+0x6df): undefined reference to `mmbit_maxlevel_direct_lut'
ch_runtime.c:(.text+0x6e9): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x728): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x766): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x79c): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x7d6): undefined reference to `mmbit_root_offset_from_level'
../lib/libchimera.a(ch_runtime.c.o):ch_runtime.c:(.text+0x808): more undefined references to `mmbit_root_offset_from_level' follow
../lib/libchimera.a(ch_runtime.c.o): In function `multiCallback':
ch_runtime.c:(.text+0x88b): undefined reference to `mmbit_keyshift_lut'
ch_runtime.c:(.text+0x972): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x98c): undefined reference to `mmbit_keyshift_lut'
ch_runtime.c:(.text+0xa35): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0xa43): undefined reference to `mmbit_maxlevel_direct_lut'
ch_runtime.c:(.text+0xab0): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0xaf0): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0xb31): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0xb73): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0xbb4): undefined reference to `mmbit_root_offset_from_level'
../lib/libchimera.a(ch_runtime.c.o):ch_runtime.c:(.text+0xbf5): more undefined references to `mmbit_root_offset_from_level' follow
../lib/libchimera.a(ch_runtime.c.o): In function `ch_scan':
ch_runtime.c:(.text+0x13a2): undefined reference to `mmbit_maxlevel_direct_lut'
ch_runtime.c:(.text+0x1420): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x146e): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x14ac): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x14ec): undefined reference to `mmbit_root_offset_from_level'
ch_runtime.c:(.text+0x152a): undefined reference to `mmbit_root_offset_from_level'
../lib/libchimera.a(ch_runtime.c.o):ch_runtime.c:(.text+0x1568): more undefined references to `mmbit_root_offset_from_level' follow
collect2: error: ld returned 1 exit status
make[3]: *** [bin/unit-chimera] Error 1
make[2]: *** [unit/CMakeFiles/unit-chimera.dir/all] Error 2
make[1]: *** [unit/CMakeFiles/unit-chimera.dir/rule] Error 2
make: *** [unit-chimera] Error 2
```

this happens while linking unit-chimera

**Comment by vectorzjl** [comment]
how to build chimera

**Comment by xiangwang1** [comment]
Can you share your build command with us?

**Comment by vectorzjl** [comment]
CMAKE:

 cmake ../$HYPERSCAN \
                -DCMAKE_INSTALL_PREFIX=$PREFIX/$HYPERSCAN \
                -DCMAKE_C_COMPILER=$PREFIX/$GCC7/bin/gcc \
                -DCMAKE_CXX_COMPILER=$PREFIX/$GCC7/bin/g++ \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_STATIC_AND_SHARED=yes \
                -DBOOST_ROOT=$PREFIX/$BOOST \
                -DFAT_RUNTIME=true \
                -DBUILD_CHIMERA=true \
                -Wno-dev

ERROR INFO:
../../lib/libchimera.a(ch_runtime.c.o)：在函数‘scanPcre.isra.10’中：
ch_runtime.c:(.text+0x286)：对‘_pcre_valid_utf’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [bin/hsbench] 错误 1
make[1]: *** [tools/hsbench/CMakeFiles/hsbench.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 94%] Linking CXX executable ../bin/unit-chimera
../lib/libchimera.a(ch_runtime.c.o)：在函数‘scanPcre.isra.10’中：
ch_runtime.c:(.text+0x286)：对‘_pcre_valid_utf’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [bin/unit-chimera] 错误 1
make[1]: *** [unit/CMakeFiles/unit-chimera.dir/all] 错误 2
[ 94%] Linking CXX executable ../../bin/hscollider
../../lib/libchimera.a(ch_runtime.c.o)：在函数‘scanPcre.isra.10’中：
ch_runtime.c:(.text+0x286)：对‘_pcre_valid_utf’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [bin/hscollider] 错误 1
make[1]: *** [tools/hscollider/CMakeFiles/hscollider.dir/all] 错误 2
[ 94%] Built target hs_compile_shared
make: *** [all] 错误 2



How to solve this error

**Comment by xiangwang1** [comment]
The reason you can't find _pcre_valid_utf() function is due to the fact that unicode support is by default off in PCRE. It is only enabled if you build PCRE with unicode support by specifying --enable-unicode-properties at configuration stage.

**Comment by vectorzjl** [comment]
It doesn't seem to work.Errors still exist.
![image](https://user-images.githubusercontent.com/26128614/56487293-4cdc5880-650d-11e9-8854-851c4b724af1.png)

**Comment by xiangwang1** [comment]
Can you put pcre source file directory under hyperscan root directory and give a try? You should see  "PCRE version 8.41 or above - building from source." when you configure hyperscan with `cmake ../$HYPERSCAN`

**Comment by vectorzjl** [comment]
-- Build type RELEASE
-- Boost version: 1.60.0
-- Build date: 2019-04-22
-- Building shared libraries
-- gcc version 4.8.5
-- g++ version 4.8.5
-- generator is Unix Makefiles
-- Building runtime for multiple microarchitectures
-- Sphinx not found, unable to generate developer reference
-- PCRE version 8.41 or above
-- Configuring done
-- Generating done

**Comment by vectorzjl** [comment]
This function _pcre_valid_utf()  is not found in the PCRE source code. Are you sure it's an internal function in pcre?
![image](https://user-images.githubusercontent.com/26128614/56490505-017b7780-6518-11e9-9f46-ae2e7dbcc355.png)

**Comment by vectorzjl** [comment]
CMAKE:

cmake ../$HYPERSCAN 
-DCMAKE_INSTALL_PREFIX=$PREFIX/$HYPERSCAN 
-DCMAKE_C_COMPILER=$PREFIX/$GCC7/bin/gcc 
-DCMAKE_CXX_COMPILER=$PREFIX/$GCC7/bin/g++ 
-DCMAKE_BUILD_TYPE=Release 
-DBUILD_STATIC_AND_SHARED=yes 
-DBOOST_ROOT=$PREFIX/$BOOST 
**-DPCRE_SOURCE=$PCRE_SOURCE**
-DFAT_RUNTIME=true 
-DBUILD_CHIMERA=true 
-Wno-dev

Successfully compile library files using the pcre source path

**Comment by JackLiar** [comment]
@xiangwang1 what I did is pretty much the same as vectorzjl.

I linked boost headers into hyperscan-5.1.1/include, and linked pcre-8.41 source code folder into hyperscan-5.1.1, cmake options are:
```cmake
cmake
    -DCMAKE_INSTALL_PREFIX=/opt/chimera \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=on \
    -DBUILD_CHIMERA=true \
    ..
```

```
[root@0c82ba97a29d hyperscan-5.1.1]# ll
total 124
-rw-rw-r--  1 root root 14053 Apr 10 14:59 CHANGELOG.md
-rw-rw-r--  1 root root 45689 Apr 10 14:59 CMakeLists.txt
-rw-rw-r--  1 root root  1478 Apr 10 14:59 COPYING
-rw-rw-r--  1 root root  6013 Apr 10 14:59 LICENSE
-rw-rw-r--  1 root root  1597 Apr 10 14:59 README.md
drwxr-xr-x 13 root root  4096 Apr 22 23:37 build
drwxrwxr-x  2 root root  4096 Apr 10 14:59 chimera
drwxrwxr-x  2 root root  4096 Apr 10 14:59 cmake
drwxrwxr-x  3 root root  4096 Apr 10 14:59 doc
drwxrwxr-x  2 root root  4096 Apr 10 14:59 examples
drwxrwxr-x  3 root root  4096 Apr 20 04:50 include
-rw-rw-r--  1 root root   333 Apr 10 14:59 libhs.pc.in
lrwxrwxrwx  1 root root    15 Apr 20 04:35 pcre-8.41 -> /root/pcre-8.41
drwxrwxr-x 12 root root  4096 Apr 10 14:59 src
drwxrwxr-x  6 root root  4096 Apr 10 14:59 tools
drwxrwxr-x  6 root root  4096 Apr 10 14:59 unit
drwxrwxr-x  2 root root  4096 Apr 10 14:59 util

[root@0c82ba97a29d hyperscan-5.1.1]# ll include/
total 4
lrwxrwxrwx 1 root root   24 Apr 20 04:50 boost -> /root/boost_1_70_0/boost
drwxrwxr-x 3 root root 4096 Apr 10 14:59 boost-patched
```

**Comment by xiangwang1** [comment]
First, users shouldn't enforce the build of Chimera by adding `-DBUILD_CHIMERA` option. We will decide whether to build Chimera internally in CMake file.

Since Chimera current doesn't support shared library build, please don't turn on `-DBUILD_SHARED_LIBS=on` and `-DBUILD_CHIMERA=true` at the same time.

**Comment by JackLiar** [comment]
@xiangwang1 thx for u advice!

There aren't too much documentations about the building process/options of chimera in chimera.rst. Hope u guys can write them more specifically in the future :)

**Comment by simpleyetawesomeprojects** [comment]
@JackLiar @vectorzjl I'm trying to build chimera and seeing the same issue. Could you share the cmake command that ran successfully for you? 

I'm using the following commands but I'm seeing error for `__pcre_valid_utf`


`PLATFORM=mac
mkdir -p $PLATFORM
cd $PLATFORM
INSTALL_PATH=`pwd`
mkdir -p include lib
mkdir -p include/hs
echo "Decompressing hyperscan..."
tar -xzvf ../hyperscan-$HYPERSCAN_VERSION.tar.gz

echo "Decompressing boost... this could take a while..."
tar --totals -xf ../boost_$BOOST.tar.gz

cd boost_$BOOST
./bootstrap.sh --with-libraries=headers
./b2 headers
cd ..

ln -sf $INSTALL_PATH/boost_$BOOST/boost $INSTALL_PATH/hyperscan-$HYPERSCAN_VERSION/include/boost

echo "Decompressing Ragel..."
tar -xzvf ../ragel-$RAGEL_VERSION.tar.gz
cd ragel-$RAGEL_VERSION
./configure --prefix="$INSTALL_PATH/.."
make -j $MAKEJ
make install
cd ..

echo "Decompressing PCRE..."
tar -xzvf ../pcre-$PCRE_VERSION.tar.gz
mv pcre-$PCRE_VERSION hyperscan-$HYPERSCAN_VERSION

cd hyperscan-$HYPERSCAN_VERSION
cd pcre-$PCRE_VERSION
./configure --enable-unicode-properties
cd ..


cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -DCMAKE_INSTALL_LIBDIR="lib" -DARCH_OPT_FLAGS='-Wno-dev' -DBUILD_STATIC_LIBS=on -DPCRE_SOURCE="pcre-$PCRE_VERSION" .

make -j 4
make install/strip`

**Comment by may11544** [comment]
> [@xiangwang1](https://github.com/xiangwang1)谢谢你的建议！
> 
> chimera.rst 中关于 chimera 的构建过程/选项的文档不多。希望大家以后能更详细地写出来 :)

I would like to ask how to solve this problem. When I build, I get errors such as lib/libchimera.a(ch_runtime.c.o): in function `isValidUTF8': and ch_runtime.c:142:(.text+0x1e4): undefined reference to `_pcre_valid_utf'. I looked at the source code of pcre-8.41 and found that there is no _pcre_valid_utf function.
