### ISSUE TITLE
ARM and PowerPC porting

### ISSUE THREAD

**Issue by danlark1** [intel/hyperscan#159]
Hi there. I would like to know if you are interested in porting hyperscan to ARM or PowerPC build. I have done a lot of work for porting most of the SSSE3 intrinsics as a part of the experiment at my company. Although not all of them are presented but it can be a challenge to make them all.

Here are examples of how it can be:
https://github.com/catboost/catboost/blob/master/library/sse/sse2neon.h
https://github.com/catboost/catboost/blob/master/library/sse/powerpc.h

Are you interested in that?

**Comment by xiangwang1** [comment]
Hi, Hyperscan is highly optimized for Intel architecture, which means the selection of algorithms and corresponding implementation is specifically targeting for Intel CPUs . Simply porting the intrinsics won't give the best performance on other platforms.

**Comment by xiaofengren** [comment]
> Hi there. I would like to know if you are interested in porting hyperscan to ARM or PowerPC build. I have done a lot of work for porting most of the SSSE3 intrinsics as a part of the experiment at my company. Although not all of them are presented but it can be a challenge to make them all.
> 
> Here are examples of how it can be:
> https://github.com/catboost/catboost/blob/master/library/sse/sse2neon.h
> https://github.com/catboost/catboost/blob/master/library/sse/powerpc.h
> 
> Are you interested in that?

May I know whether you can share more information about how to integrate sse2neon to hyperscan? Do you get one chance to measure performance on ARM platform?

**Comment by xishi123** [comment]
> Hi there. I would like to know if you are interested in porting hyperscan to ARM or PowerPC build. I have done a lot of work for porting most of the SSSE3 intrinsics as a part of the experiment at my company. Although not all of them are presented but it can be a challenge to make them all.
> 
> Here are examples of how it can be:
> https://github.com/catboost/catboost/blob/master/library/sse/sse2neon.h
> https://github.com/catboost/catboost/blob/master/library/sse/powerpc.h
> 
> Are you interested in that?

Hi, I'm interested in hyperscan on ARM(aarch64), could you share your arm hyperscan code?

**Comment by adolia** [comment]
> Hi there. I would like to know if you are interested in porting hyperscan to ARM or PowerPC build. I have done a lot of work for porting most of the SSSE3 intrinsics as a part of the experiment at my company. Although not all of them are presented but it can be a challenge to make them all.
> 
> Here are examples of how it can be:
> https://github.com/catboost/catboost/blob/master/library/sse/sse2neon.h
> https://github.com/catboost/catboost/blob/master/library/sse/powerpc.h
> 
> Are you interested in that?

Hi, I'm interested in porting hyperscan to ARM, can you share more information about that?

**Comment by kriao** [comment]
i, I'm interested in porting hyperscan to ARM, can you share more information about that?

**Comment by kriao** [comment]
> Hi there. I would like to know if you are interested in porting hyperscan to ARM or PowerPC build. I have done a lot of work for porting most of the SSSE3 intrinsics as a part of the experiment at my company. Although not all of them are presented but it can be a challenge to make them all.
> 
> Here are examples of how it can be:
> https://github.com/catboost/catboost/blob/master/library/sse/sse2neon.h
> https://github.com/catboost/catboost/blob/master/library/sse/powerpc.h
> 
> Are you interested in that?

i, I'm interested in porting hyperscan to ARM, can you share more information about that?
