### ISSUE TITLE
Question about format conversion between Snort rule and Hyperscan rule

### ISSUE THREAD

**Issue by JamiesZhang** [intel/hyperscan#162]
The format of Snort rule and Hyperscan rule is different, are there some direct ways to convert them?

**Comment by xiangwang1** [comment]
Snort is an IDS/IPS system while Hyperscan is a regex matching library. So naturally they are solving different kinds of problems and it doesn't make much sense to do the conversion. But Snort takes advantage of regex matching to matching packet payload with regex patterns defined in its rules. You can write scripts to extract regex patterns in the "pcre" field of Snort rules.
