### ISSUE TITLE
the Chinese period （。）match the pattern [\u4E00-\u9FA5]

### ISSUE THREAD

**Issue by whhitdragon** [intel/hyperscan#164]
I compile the pattern of [\u4E00-\u9FA5] with default flags, when i using chines period（。）to match the pattern，the result is matched.According to the actual situation,the resule must be not matched.

**Comment by xiangwang1** [comment]
I don't think Hyperscan is able to compile this pattern. Can you give the exact pattern passed to Hyperscan?

**Comment by whhitdragon** [comment]
The hyperscan can support this pattern, and can running. This pattern is to detect  if give string contains Chinese characters.

hs_compile("[\u4E00-\u9FA5]", HS_FLAG_MULTILINE | HS_FLAG_DOTALL | HS_FLAG_ALLOWEMPTY , HS_MODE_BLOCK, NULL, &m_pHsDatabase, &compile_error);

**Comment by xiangwang1** [comment]
You can't hardcode unicode points within double quotation in your source code file in this way. 

`[\u4E00-\u9FA5]` will be interpreted as `[\xe4\xb8\x80-\xe9\xbe\xa5]` when passing to hs_compile() where `\u4e00` is replaced by `\xe4\xb8\x80` and `\u9FA5` is replaced by `\xe9\xbe\xa5`. This pattern will be finally simplified to `[\x80-\e90]` in Hyperscan.

If you read a file containing this pattern, the result will be different.

**Comment by whhitdragon** [comment]
@xiangwang1
This is a simple code.  [一-龥] is the pattern in the file. I want to match Chinese characters，how to write the pattern？
According to what you( this pattern will be finally simplified to [\x80-\e90] in Hyperscan), the final patten is not the original meaning.

**Comment by xiangwang1** [comment]
I think you can use `\p{Han}`.

**Comment by whhitdragon** [comment]
@xiangwang1 
I test using the simplegrep:

[root@localhost bin]# ./simplegrep "[一-龥]" 1.txt 
Scanning 13 bytes with Hyperscan
Match for pattern "[一-龥]" at offset 1

1.txt content is :
。，】、

running according to what you , the result fllows:
[root@localhost bin]# ./simplegrep "\p{Han}" 1.txt 
ERROR: Unable to compile pattern "\p{Han}": Pattern can never match.

**Comment by xiangwang1** [comment]
HS_FLAG_UTF8 | HS_FLAG_UCP

**Comment by whhitdragon** [comment]
@xiangwang1 

Tks for your help!

**Comment by xiangwang1** [comment]
Close as this isn't a Hyperscan issue.
