### ISSUE TITLE
stream mode & logical combination

### ISSUE THREAD

**Issue by playboy123fan** [intel/hyperscan#165]
hyperscan version:5.1.0

I choose the stream mode, and there're some logical combination expressions, for example,{101,102,101&102},101&102 is the combination expression. There're 5 packets in one stream, expression 101 matches at offset 10 and expression 102 matches at offset 20 in the first packet,  hs returns sub-expression 101 and sub-expression 102 immediately, and it returns the combination expression 101&102 when the stream is over or other expression matches in the stream. Is this normal?

**Comment by fatchanghao** [comment]
Hi, a sub-expression matching should not affect unrelated combination, could you provide the exact case you use so that we can take a deep look?

**Comment by playboy123fan** [comment]
@fatchanghao 
Hi, 
src:  
![企业微信截图_20190603093435](https://user-images.githubusercontent.com/51144435/58773582-2c191f80-85f0-11e9-9b4d-97283db9f942.png)  
![企业微信截图_20190603095324](https://user-images.githubusercontent.com/51144435/58773606-42bf7680-85f0-11e9-9a6f-a4887a557dca.png)
![企业微信截图_20190603110024](https://user-images.githubusercontent.com/51144435/58773622-5834a080-85f0-11e9-949e-1d5f3b80711f.png)
testfile:
![企业微信截图_20190603105907](https://user-images.githubusercontent.com/51144435/58773662-82865e00-85f0-11e9-92c3-6362cf86b294.png)
![企业微信截图_20190603105932](https://user-images.githubusercontent.com/51144435/58773668-8619e500-85f0-11e9-9222-1db41e68397c.png)
![企业微信截图_20190603105951](https://user-images.githubusercontent.com/51144435/58773672-8ade9900-85f0-11e9-8119-7c40ec1839a6.png)
result:  
![企业微信截图_20190603105854](https://user-images.githubusercontent.com/51144435/58773678-9336d400-85f0-11e9-9095-38edb14b96dc.png)

**Comment by fatchanghao** [comment]
Thanks for the detail! Seems it's a new issue in streaming mode from v5.1, we'll fix it in the coming release.

**Comment by Nor7th** [comment]
Fixed in 5.2.0
