### ISSUE TITLE
Is it going to work if I try to use if with AMD processor?

### ISSUE THREAD

**Issue by evandrocoan** [intel/hyperscan#169]
I got the impression this is tight tied to Intel Processors. If I build a binary of this project and it it on a AMD processor, is it going to work or it will just run slower?

**Comment by xiangwang1** [comment]
Hyperscan works on AMD, but we only do optimizations for Intel architecture. So Hyperscan runs best on Intel and there could be performance degradation on AMD.

**Comment by MutableLoss** [comment]
Since the addition of AVX512 to the AMD Epyc cores, are there any plans to include AVX512 support for these cores?
