### ISSUE TITLE
If my input data has invalid ASCII or UTF8 characthers, what happens? Are they ignored?

### ISSUE THREAD

**Issue by evandrocoan** [intel/hyperscan#170]
The documentation say this about UTF8:
> [`HS_FLAG_UTF8`](http://intel.github.io/hyperscan/dev-reference/api_files.html#c.HS_FLAG_UTF8)
Compile flag: Enable UTF-8 mode for this expression.
This flag instructs Hyperscan to treat the pattern as a sequence of UTF-8 characters. The results of scanning invalid UTF-8 sequences with a Hyperscan library that has been compiled with one or more patterns using this flag are undefined.

I am not using the `HS_FLAG_UTF8` as am not interested in matching UTF8 stuff, I compile my regex with this:
```c++
const char* = "(simple pure ASCII regex)";
hs_compile( rawregex, HS_FLAG_SINGLEMATCH | HS_FLAG_DOTALL, 
            HS_MODE_BLOCK, NULL, &compiledregex, &compile_err )

const char* readline = "I am a ASCII text with some 🤩 nuts stuff";
hs_scan( compiledregex, readline, charsread, 0, scratchspace, null_onEvent, NULL )
```

The problem is that the input text I parse with `hs_scan` may contain invalid UTF8 characters. Are they ignored by `hyperscan` or do I need to do preparsing removing these characters?

These invalid characters are very rare and happens about one time each 1.000.000.000 chars. So, I am hesitant to include this overhead on the input data.

**Comment by xiangwang1** [comment]
Hyperscan itself doesn't have any UTF8 check on your input and instead process your input as separate byte characters no matter `HS_FLAG_UTF8` is on or off. Users should guarantee UTF8 validness in UTF8 mode.

In your case, invalid UTF8 characters will be processed by Hyperscan as normal bytes as well. If this will impact the final match results, I believe you have to do preparsing for your input.

**Comment by evandrocoan** [comment]
Thanks for clarifying!!
