### ISSUE TITLE
can Chimera be serialized or deserialized?

### ISSUE THREAD

**Issue by ericxsun** [intel/hyperscan#175]
Any apis to serialize or deserialize Chimera class like the apis to [serialize-hs_serialize_database](https://github.com/intel/hyperscan/blob/master/src/hs_common.h) / [deserialize - hs_deserialize_database](https://github.com/intel/hyperscan/blob/master/src/hs_common.h) Hyperscan?

any help will be highly appreciated

**Comment by xiangwang1** [comment]
Since Chimera is a hybrid of PCRE and Hyperscan, the generated database contains both PCRE part and Hyperscan part. Unfortunately, we can't support serialization due to PCRE's incapability of serialization.

**Comment by ericxsun** [comment]
Thanks anyway
