### ISSUE TITLE
Can Hyperscan support binary scanning?

### ISSUE THREAD

**Issue by wangxi19** [intel/hyperscan#177]
某些原因, 我需要二进制模式扫描.  
如: 用hs.scan扫描给定一段内存数据 char buf[]{0, 72, 69, 76, 76, 79},
 代表 "\0HELLO"， 对应的 Hyperscan pattern 怎样写？
在 re2 中 我可以直接写成 R"(\x00HELLO)"

In some reason, I need Hyperscan's binary scanning mode.
example: use hs.scan to scan the memory buffer  char buf[]{0, 72, 69, 76, 76, 79} which represent the string "\0HELLO", how do I write the corresponding pattern?
I can write R"(\x00HELLO)" directly in re2.

**Comment by fatchanghao** [comment]
In your case you can just write "\x00HELLO".

**Comment by wangxi19** [comment]
I had tried it before I write the issue. It isn't useful.
if use "\x00HELLO", the pattern is equal to "" because it start with "\x00", so when I call hs_compile_multi() to build pattern, I will get a error: HS_FLAG_ALLOWEMPTY should be turned on.

And I also have used R("\x00HELLO"), in this case, calling hs_compile_multi() will be success, but cann't scan out result

**Comment by xiangwang1** [comment]
If you are hardcoding patterns directly in your program, could you please try "\\x00HELLO"?

**Comment by wangxi19** [comment]
> If you are hardcoding patterns directly in your program, could you please try "\\x00HELLO"?

Thanks, but using R("\x00HELLO") is equal to "\\x00HELLO" in hardcode.
Can you use "\\x00HELLO" to match successfully?
