### ISSUE TITLE
The same pattern within a single line is matched only once

### ISSUE THREAD

**Issue by dvaldivia** [intel/hyperscan#178]
Hi, I'm compiling the following pattern to match IPs but Hyperscan is only matching once

Pattern
```
(((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9]))
```
with the flags `HS_FLAG_CASELESS` and `HS_FLAG_SOM_LEFTMOST`

for a given line
```
192.168.0.1 "quoted2" 10.20.30.40
```
The pattern is only being matched once, how can I have the pattern match the second ip within the same input line?

**Comment by Nor7th** [comment]
Hi,

Not sure how you carry out the test. But the following code works fine:

    #include <hs.h>
    #include <cassert>
    #include <string>
    
    int callback(unsigned int id, unsigned long long from, unsigned long long to,
           unsigned int flags, void *context) {
        printf("id=%u, from=%lld, to=%lld\n", id, from, to);
        return 0;
    }
    
    int main() {
        hs_database_t *db = nullptr;
        hs_compile_error_t *compile_err = nullptr;
    
        // the double quotation marks around quated2 should be backslashed here.
        std::string data = "192.168.0.1 \"quoted2\" 10.20.30.40";
        const char *expr = "(((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9]))";
        unsigned flag = HS_FLAG_CASELESS | HS_FLAG_SOM_LEFTMOST;
    
        hs_error_t err = hs_compile(expr, flag, HS_MODE_BLOCK, nullptr, &db, &compile_err);
    
        assert(HS_SUCCESS == err);
        assert(db != nullptr);
    
        hs_scratch_t *scratch = nullptr;
        err = hs_alloc_scratch(db, &scratch);
        assert(HS_SUCCESS == err);
        assert(scratch != nullptr);
    
        err = hs_scan(db, data.c_str(), data.size(), 0, scratch, callback, nullptr);
        assert(HS_SUCCESS == err);
    
        hs_free_database(db);
        err = hs_free_scratch(scratch);
        assert(HS_SUCCESS == err);
    }

The output result of callback is:
    `id=0, from=0, to=11`
    `id=0, from=22, to=32`
    `id=0, from=22, to=33`

Offset from 0 to 11 indicates substring "192.168.0.1"
Offset from 22 to 32 indicates substring "10.20.30.4"
Offset from 22 to 33 indicates substring "10.20.30.40"
