### ISSUE TITLE
A question regarding the code

### ISSUE THREAD

**Issue by shlyakpavel** [intel/hyperscan#184]
Could someone please explain the magic here?
https://github.com/intel/hyperscan/blob/4cebdaa435f1f52e96450e066937b3835b9b7047/util/ng_corpus_generator.cpp#L486-L488
I'm especially interested in `=+` stuff

**Comment by xiangwang1** [comment]
I think this code aims to skip code points between UNICODE_SURROGATE_MIN and UNICODE_SURROGATE_MAX which are not useful. Adding UNICODE_SURROGATE_MAX is probably the most convenient and concise way.

**Comment by shlyakpavel** [comment]
> Adding UNICODE_SURROGATE_MAX

Would look like `c += UNICODE_SURROGATE_MAX + 1;`
The present code is *setting* `c` to `UNICODE_SURROGATE_MAX + 1`, which is equal to
`c = UNICODE_SURROGATE_MAX + 1`.
I would personally prefer to change to either to += or to = (up to whatever original author meant) to avoid confusions.

**Comment by xiangwang1** [comment]
Thanks, we'll change it.

**Comment by shlyakpavel** [comment]
@xiangwang1 it looks like the issue is still not resolved

**Comment by shlyakpavel** [comment]
@xiangwang1 the issue is still not resolved

**Comment by fatchanghao** [comment]
updated on "develop" branch.
