### ISSUE TITLE
building 5.2.0 for fedora

### ISSUE THREAD

**Issue by jmtaylor90** [intel/hyperscan#186]
I am working on getting the new version into fedora but am running into some build issues. This is the version the watcher service attempted to build but my attempt met with the same results. The errors seem related to hscheck and hsbench, a snippet of the build.log:

BUILDSTDERR: cd /builddir/build/BUILD/hyperscan-5.2.0/tools/hsbench && /usr/bin/c++   -I/builddir/build/BUILD/hyperscan-5.2.0/tools/hsbench -I/builddir/build/BUILD/hyperscan-5.2.0/src -I/builddir/build/BUILD/hyperscan-5.2.0 -I/builddir/build/BUILD/hyperscan-5.2.0/tools/src -I/builddir/build/BUILD/hyperscan-5.2.0/util -isystem /builddir/build/BUILD/hyperscan-5.2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -std=c++11 -Wall -Wextra -Wshadow -Wswitch -Wreturn-type -Wcast-qual -Wno-deprecated -Wnon-virtual-dtor -fno-strict-aliasing -DNDEBUG -Wno-maybe-unin/usr/bin/ld: CMakeFiles/hscheck.dir/main.cpp.o: in function `checkExpression(void*)':
BUILDSTDERR: /builddir/build/BUILD/hyperscan-5.2.0/tools/hscheck/main.cpp:339: undefined reference to `ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&)'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[2]: *** [tools/hscheck/CMakeFiles/hscheck.dir/build.make:89: bin/hscheck] Error 1
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:822: tools/hscheck/CMakeFiles/hscheck.dir/all] Error 2
BUILDSTDERR: make[1]: *** Waiting for unfinished jobs....
itialized -Wno-abi -fno-omit-frame-pointer -fvisibility=hidden -Wvla -Wpointer-arith -Wno-unused-const-variable -Wno-ignored-attributes -Wmissing-declarations  -g -DNDEBUG   -o CMakeFiles/hsbench.dir/engine.cpp.o -c /builddir/build/BUILD/hyperscan-5.2.0/tools/hsbench/engine.cpp

BUILDSTDERR: cd /builddir/build/BUILD/hyperscan-5.2.0/unit && /usr/bin/c++  -DGTEST_HAS_PTHREAD=0 -DSRCDIR=/builddir/build/BUILD/hyperscan-5.2.0 -I/builddir/build/BUILD/hyperscan-5.2.0/src -I/builddir/build/BUILD/hyperscan-5.2.0 -isystem /builddir/build/BUILD/hyperscan-5.2.0/unit -isystem /builddir/build/BUILD/hyperscan-5.2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -std=c++11 -Wall -Wextra -Wshadow -Wswitch -Wreturn-type -Wcast-qual -Wno-dep/usr/bin/ld: CMakeFiles/hsbench.dir/engine_hyperscan.cpp.o: in function `buildEngineHyperscan(std::map<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, ScanMode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ue2::Grey const&)':
BUILDSTDERR: /builddir/build/BUILD/hyperscan-5.2.0/tools/hsbench/engine_hyperscan.cpp:431: undefined reference to `ue2::hs_compile_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&)'
BUILDSTDERR: /usr/bin/ld: /builddir/build/BUILD/hyperscan-5.2.0/tools/hsbench/engine_hyperscan.cpp:424: undefined reference to `ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&)'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[2]: *** [tools/hsbench/CMakeFiles/hsbench.dir/build.make:180: bin/hsbench] Error 1

https://koji.fedoraproject.org/koji/taskinfo?taskID=37084351
https://kojipkgs.fedoraproject.org//work/tasks/4351/37084351/build.log

Any pointers/assistance would be appreciated. Thanks in advance!

**Comment by Nor7th** [comment]
Hi,
This problem appears particularly in release+shared_lib mode, which is due to a misuse of an internal function.
Thanks for reporting this issue. We shall have a minor release recently.

**Comment by cdyson37** [comment]
Does anyone have a patch to work around this?

**Comment by jmtaylor90** [comment]
I haven't had a chance to dig into it more to create one. Any time frame on the minor release for this @Nor7th ?

**Comment by Nor7th** [comment]
The release shall be ready in 2 weeks. Sorry for keep you waiting :)

**Comment by Nor7th** [comment]
Please refer to new release 5.2.1

**Comment by jmtaylor90** [comment]
This appears to be resolved in 5.2.1, thank you!
