### ISSUE TITLE
The Maillist link is down

### ISSUE THREAD

**Issue by bzhaoopenstack** [intel/hyperscan#196]
https://lists.01.org/mailman/listinfo/hyperscan
This link from homepage is down. Any body could provider the maillist for the newbees or make the link up again? 
Thanks very much.

**Comment by bzhaoopenstack** [comment]
Hi @xiangwang1 , I found the recent issues are replied by you, so I guess you may be around. ;-) Could you please try to fix it? And I will have another questions to ask you. Thank you very much.

**Comment by bzhaoopenstack** [comment]
Hi @Nor7th , @fatchanghao ,
And so apologize for disturbing you and @xiangwang1.
 I notice that you may also around. ;-）. Could you please give the community maillist to me? And if we have some new feature to introduce  into hyperscan, I found there are only 3 ways to access you guys.
1) Issue in github repo to discuss(available)
2) send emails to community maillist to discuss(unavailable Now)
3) send emails to hyperscan@intel.com
So I wanna ask you that which way is easiest to our discussion, quickly reply and chat frequently? Because I realize that all of us are in China. ;-)

Thank you very much.

**Comment by xiangwang1** [comment]
Hi @bzhaoopenstack , will this link work for you: https://lists.01.org/postorius/lists/hyperscan.lists.01.org/.

It will be good to discuss via mailing list or email if your issue is not bug related.

**Comment by bzhaoopenstack** [comment]
Hi @xiangwang1 ,
Thanks very much, it works.
That sounds good. I will try to subscribe the list. ;-). Thank you

**Comment by bzhaoopenstack** [comment]
Oh,  seems the link is working, but I still receive "Confirmation token did not match" from confirmation emails. I had sent out an email to "hyperscan-owner@lists.01.org" for asking help to subcribe. ;-)

**Comment by bzhaoopenstack** [comment]
Hi @xiangwang1 ,
I  had sent out a email to hyperscan@lists.01.org for discussing what we care. Hoping you guys could join in, also we can trace the discussion here.

Thanks
