### ISSUE TITLE
Merge pull requests

### ISSUE THREAD

**Issue by flip111** [intel/hyperscan#201]
There seem to be a bunch of open pull requests. Some of them are trivial and easy to merge. Could someone with merge access go through them and merge?

**Comment by Nor7th** [comment]
The latest 4 pull requests (#179 #183 #185 #200 ) has been picked up into `develop` branch.

**Comment by flip111** [comment]
Thats great @Nor7th what about

https://github.com/intel/hyperscan/pull/129
https://github.com/intel/hyperscan/pull/161
https://github.com/intel/hyperscan/pull/167

https://github.com/intel/hyperscan/pull/151 can be closed ? -- has merge message
https://github.com/intel/hyperscan/pull/172 can be closed ?? because of comment ` Never mind, seems to be part of 5.2.0`

still needs to be merged because has no merge message ???
https://github.com/intel/hyperscan/pull/157
https://github.com/intel/hyperscan/pull/156
https://github.com/intel/hyperscan/pull/166

**Comment by Nor7th** [comment]
For all the 8 pull requests you listed, only #129 is not merged, all the left have been already merged into 5.2.0 and can be closed for now.
Thanks for reminding us.

**Comment by flip111** [comment]
Thank you too @Nor7th i will close this now, you seem to be on top of it.

**Comment by okias** [comment]
@Nor7th  can you give me hint why it isn't merged? Any feedback please?
