### ISSUE TITLE
A question about HS_FLAG_SOM_LEFTMOST

### ISSUE THREAD

**Issue by NanXiao** [intel/hyperscan#210]
Hi,

Greeting from me!

I find following description from [HS_FLAG_SOM_LEFTMOST](https://intel.github.io/hyperscan/dev-reference/api_files.html?highlight=hs_flag_som_leftmost#c.HS_FLAG_SOM_LEFTMOST):

> Enabling this behaviour may reduce performance and increase stream state requirements in streaming mode.

Does it mean "reduce performance" only occur in streaming mode (not in block or vectored mode)? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by Nor7th** [comment]
Hi, you might understand this statement like this:

For all the 3 modes, enabling this behaviour may reduce performance. And particularly, it may increase stream state requirements in streaming mode.

**Comment by NanXiao** [comment]
@Nor7th 

Thanks very much for your answer! Maybe consider rephrase the sentences? Because I find it may make people confused.

Thanks!

**Comment by Nor7th** [comment]
We'll consider that in our next release. Thank you!

**Comment by Nor7th** [comment]
Hi NanXiao,

Is the patch email "[PATCH] Processing VLAN packets in pcapCorpus.py" also from you? We have verified it and it's fine to merge it. Could you submit a new Github pull request for this patch?

Thanks.

**Comment by NanXiao** [comment]
@ Nor7th, I submitted a PR (https://github.com/intel/hyperscan/pull/214), please check it, thanks very much!
