### ISSUE TITLE
Question: Hyperscan dependencies

### ISSUE THREAD

**Issue by kreuzerkrieg** [intel/hyperscan#224]
Hi,
I use hyperscan via `vcpkg`. In the hyperscan repo I dont see any mention of build dependencies. However, vcpkg defines handful of dependencies

>>boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utility, boost-dynamic-bitset, boost-random, boost-graph, boost-multi-array, boost-icl, boost-ptr-container, python3, ragel

Taken from [here](https://github.com/microsoft/vcpkg/blob/master/ports/hyperscan/CONTROL)

Could anyone review the list of dependencies please

**Comment by flowerysong** [comment]
Looks fairly reasonable. See https://github.com/intel/hyperscan/blob/master/doc/dev-reference/getting_started.rst#requirements

**Comment by kreuzerkrieg** [comment]
Ok then. Thanks for the info!
