### ISSUE TITLE
Use hyperscan to match single patterns

### ISSUE THREAD

**Issue by Flow-It** [intel/hyperscan#226]
I've been using hyperscan successfully to scan big texts for hundreds of thousands of regexes (most quite simple to be fair, often just literals). Now, another requirement was added. Additionally to the text chunks, regex matches will also be performed on fields of structured documents (can be XML, JSON, CSV, ...). Multiple fields are of interest, but inside a field, only very few expressions will be scanned for (often enough just a single regex or even literal).
From my understanding, I'd need to create a new pattern database for each field and populate it with those few expressions and then scan every single field of interest against its particular database.
I'm well aware that hyperscan was not designed for this use case, but I'm already using the library in my project and I'm quite happy with it.
So, is this a practicable approach? Are there any caveats with using multiple pattern databases?

**Comment by xiangwang1** [comment]
I think it's fine to generate multiple databases. We also have integrations on IDS/IPS systems (Snort and Suricata) for single regex and literal matching. 

One potential optimization is that you can have multiple databases sharing the same scratch space if they won't be used concurrently (http://intel.github.io/hyperscan/dev-reference/performance.html#allocate-one-scratch-space-per-scanning-context).
