### ISSUE TITLE
Explanation of "have unordered match in sub-expressions" for logical combinations

### ISSUE THREAD

**Issue by eskriett** [intel/hyperscan#234]
I'm currently using hyperscan's logical combinations with hyperscan 5.2.1. 

For the most part the logical combinations work great, but I've come across a few patterns that throw warnings I can find little information on.

A minimal working example of patterns that cause the issue:

```
$ cat patterns 
1:/a\b/
2:/b/
3:/1|2/C
```

When checking these patterns with `hscheck`, the following information is provided:

```
$ bin/hscheck -N -C -e patterns
OK: 1:/a\b/
OK: 2:/b/
FAIL (compile): 3:/1|2/C: Have unordered match in sub-expressions.
SUMMARY: 1 of 3 failed.
```

After a little experimentation, I believe this is because `\b` includes an end of line match, i.e. `\w$`. If I change pattern 1 above to be `/a$/` I'm provided the same error.

This problem only arises when using logical combinations, if I remove pattern 3 above, then there are no issues. 

Is this behaviour expected, and if so, could a little insight be provided into what causes the problem so I can avoid the problem in future?

Thanks for a great library,
Hayden

**Comment by fatchanghao** [comment]
Hi Hayden,

Currently Hyperscan doesn't support logical combination with sub-expression which may generate unordered match. A pattern with assertions like word boundary or line boundary cannot directly report a match at match position unless it checked the next position, if another pattern reports a match at next position earlier, then it will generate a unordered match.

Normally this kind of "unordered" pattern is supported (without logical combination), but if it's used in logical combination we may got wrong results:

Consider the following case, if we define a combination "!A&B", in which A is a "unordered" pattern. If B reports matches at 10 and 11, then the combination is TRUE and reports matches at 10 and 11. Then if A reports a match at 10 (unordered), which means the combination should be FALSE at 10, so the previously reported combinations match is wrong.

So we reject this kind of "unordered" pattern to participate in logical combination. BTW, hscheck is a useful tool to find unsupported combinations like this.

Thanks,
Harry

**Comment by eskriett** [comment]
Thanks for taking the time to explain this further, your example has provided the necessary insight to see why this isn't supported.

Hayden
