### ISSUE TITLE
What is the usecase for HS_FLAG_MULTILINE flag on pure literal dbs?

### ISSUE THREAD

**Issue by HAT-DK** [intel/hyperscan#237]
Since anchors are not supported in pure literal dbs patterns (hs_compile_lit_multi()), what is the usecase for setting the HS_FLAG_MULTILINE flag?

**Comment by Nor7th** [comment]
@HAT-DK that's right consideration, we neglect this flag. Thanks for pointing out. Will get it fixed in next release.
