### ISSUE TITLE
What architecture to target for a portable library?

### ISSUE THREAD

**Issue by eliaslevy** [intel/hyperscan#245]
The documentation talks about how the Hyperscan library will be [targeted to some architecture](https://intel.github.io/hyperscan/dev-reference/getting_started.html#target-architecture) at compile time, and how this architecture will be the build system's architecture if not building a fat runtime and a target architecture one is not specified.

But the documentation is silent on what architecture to target to ensure that a non-fat runtime compiled library can execute without issues in all supported architectures.

What architecture should one target to build a library that will work on all systems supported by Hyperscan?

**Comment by eliaslevy** [comment]
[This](https://github.com/intel/hyperscan/issues/20#issuecomment-218321603) comment indicates that the minimum is `core2`.

**Comment by xiangwang1** [comment]
Yes, you need to build with minimum instruction support with `-march=core2`

**Comment by eliaslevy** [comment]
To finish up, Visual Studio does not have a architecture target for SSSE3, but does have `/arch:AVX` which includes SSSE3 and SSE4.2, but not AVX2, so basically a minimum of Core i7 instead of Core 2.  As of VS2019, `/arch:SSE2` is the default.
