### ISSUE TITLE
[Question] Is it creating dynamically executable regions?

### ISSUE THREAD

**Issue by Unc3nZureD** [intel/hyperscan#246]
I'm curious if this library is creating any dynamically executable region at runtime. I'm asking because PCRE2 is creating a new read-write-exec page in case of JIT compilation. Is HyperScan creating such buffer in any case, or it's completely compatible in every case with ProcessDynamicCodePolicy?

Thank you very much! :)

**Comment by xiangwang1** [comment]
Hyperscan doesn't leverage any JIT techniques. 
We comply with ProcessDynamicCodePolicy and won't create any dynamically executable regions at runtime.

**Comment by Unc3nZureD** [comment]
Thank you very much! :)
