### ISSUE TITLE
Simple Literal Pattern Leads to Severe Performance Degradation

### ISSUE THREAD

**Issue by crc181** [intel/hyperscan#253]
Hi,

The following patterns demonstrate an unexpected performance hit for a buffer of ~1000 zeros.

1:/MB\x00\x00\x00\x00\x00\x00\x00\x00/H
Max throughput (per core): 258.46 Mbit/sec

2:/MB\x01\x00\x00\x00\x00\x00\x00\x00/H
Max throughput (per core): 22,771.01 Mbit/sec

3:/MB\x00\x00\x00\x00\x00\x00\x00/H
Max throughput (per core): 22,254.96 Mbit/sec

4:/MB\x00\x00\x00\x00\x00\x00\x00\x00\x00/H
Max throughput (per core): 155.13 Mbit/sec

5:/MB\x00\x00\x00\x00\x00\x00\x00\x00Z/H
Max throughput (per core): 25,423.95 Mbit/sec

Pattern 2 changes the third byte, pattern 3 removes one of the \0, and pattern 5 adds a different last byte making these patterns two orders of magnitude faster.  Pattern 4 has 9 \0.  8 or more causes the performance hit.  The same thing happens when the pattern is /MB00000000/ and the buffer is full of 0s.

It looks like the problem arises when a pattern has a suffix with 8 or more repeating bytes and the buffer is filled with the same byte.  This is something of an edge case, but pattern 1 cripples throughput for a standard perf test.  In fact, AC is 5X faster for this test.

Another wrinkle is that combinations that include pattern 1 don't always perform as poorly.  Patterns 1 and 2 together only down by half:

Max throughput (per core): 12,569.60 Mbit/sec

We can work around this particular pattern, but it could be afflicting other patterns that we aren't yet aware of so I'm hoping you can provide some guidance on what to look out for if it is not something that can be fixed.

This may be related to #68 .

Thanks!

**Comment by xiangwang1** [comment]
Thanks for the details. This is highly related to Hyperscan's internal literal matching mechanism that only matches 8-byte suffix quickly and in most cases will filter out uninteresting input string.  
That's the reason why we get extremely high performance for pattern 2, 3 and 5. 

However, if the 8-byte suffix is a full match then we have to trigger a generic scheduler to handle all sorts of cases as the prefix part could be a pure literal, a regex, a combination of literal and regex, etc. The scheduler contains complex logic that is too heavy for simple cases such as pattern 1 and 4.

We have an optimization when pattern 1 and 2 are compiled together, and I think we can also apply it for single pattern cases to at least get similar performance.

**Comment by crc181** [comment]
Thanks.  We're going to try to steer clear of the all null suffixes.  Beyond that, we'll have to watch for any suffixes with repeating subpatterns.
