### ISSUE TITLE
hyperscan cmake编译选项问题

### ISSUE THREAD

**Issue by SQBLXHQ** [intel/hyperscan#254]
您好,我在编译hyperscan源码时，使用命令cmake -DCMAKE_BUILD_TYPE=Debug，指定DCMAKE_BUILD_TYPE为Debug模式，但我发现使用gdb调试代码时仍有一部分变量的值为optimized out状态，并且代码中的DEBUG_PRINTF宏也没有调用，想问一下是否有其他的参数选项需要在设置debug模式时指定？

![2 {SZ7_(0 ( Y$04GU20DPT](https://user-images.githubusercontent.com/34790358/87275094-014a0c00-c510-11ea-9106-1cc165c79f6c.png)

**Comment by fatchanghao** [comment]
You can try -DDEBUG_OUTPUT=1

**Comment by SQBLXHQ** [comment]
> 您可以尝试-DDEBUG_OUTPUT = 1
好的，非常感谢您的回复
