### ISSUE TITLE
Issue in building Hyperscan for Windows

### ISSUE THREAD

**Issue by KavinMotlani** [intel/hyperscan#255]
I am trying to build the static library for Hyperscan for Windows. I followed the instructions [here](https://software.intel.com/content/www/us/en/develop/articles/get-started-with-hyperscan-on-windows.html) and was able to build ragel and get all the dependencies installed. When I am trying to create the configuration with cmake using the command "CMake -G "Visual Studio 15 2017 Win64" -D BOOST_ROOT=%cd%/../boost_1_73_0/.." I am getting the following error:

$ CMake -G "Visual Studio 15 2017 Win64" -D BOOST_ROOT=%cd%/../boost_1_73_0/..
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.14393.
-- Build type RELWITHDEBINFO
-- using release build
-- Boost version: 1.73.0
-- Build date: 2020-07-15
-- Building static libraries
-- Building for Windows
CMake Error at cmake/arch.cmake:10 (message):
  No intrinsics header found
Call Stack (most recent call first):
  CMakeLists.txt:332 (include)

-- Configuring incomplete, errors occurred!
See also "C:/cygwin64/home/kamotlan/hyperscan/CMakeFiles/CMakeOutput.log".

Any pointers on how to resolve this?

**Comment by KavinMotlani** [comment]
Used vcpkg to build for windows

**Comment by shaybarak11** [comment]
hey @KavinMotlani 
Can you help me out to build hyperscan for windows?
