### ISSUE TITLE
Can't Build on KVM

### ISSUE THREAD

**Issue by MyLike2018** [intel/hyperscan#258]
when i  build the source code on kvm , it is OK.  But when the install is finished, i run the unit-hyperscan, there are many erros.
![image](https://user-images.githubusercontent.com/43329837/87874659-1c2feb00-c9fe-11ea-9b60-fd5fbb0a06a8.png)

cpu info is below:
![image](https://user-images.githubusercontent.com/43329837/87874677-4c778980-c9fe-11ea-9351-f2fbf3ec0895.png)

Build Action:
cmake ../<hyperscan_dir>=======>the configure is pass
make -j4

i want to ask, how to solve it and install rightly?

**Comment by xiangwang1** [comment]
Hyperscan requires a minimum of SSSE3 instruction-set support, while your CPU info doesn't have this flag. Can you check your configuration for it?

**Comment by MyLike2018** [comment]
![image](https://user-images.githubusercontent.com/43329837/87891652-3fde4a00-ca6d-11ea-8a2c-29b16fcf4e36.png)

**Comment by xiangwang1** [comment]
But your virtual machine doesn't have ssse3 flag. Can you check the configuration of your virtual machine or any interference from host machine?

**Comment by MyLike2018** [comment]
Thanks for your help,
How do you find the detail: my virtual machine doesn't have ssse3 flag?
but the result above is from my virtual machine, i don't know this is what you said?
And could you tell me how to check the configure of the virtual machine?

**Comment by xiangwang1** [comment]
Because the `flags` row of your CPU info only has SSE2 flag but not SSSE3 flag.

![image](https://user-images.githubusercontent.com/15205002/87899759-c05c7500-ca84-11ea-8a87-ac740f9cbf02.png)

**Comment by MyLike2018** [comment]
i know, much thanks.

is there also some ways to use when it built without ssse3 flag?

**Comment by xiangwang1** [comment]
No, SSSE3 is our minimum requirement.
