### ISSUE TITLE
Build examples optionally

### ISSUE THREAD

**Issue by Flow-It** [intel/hyperscan#260]
I'm currently working on providing a conan recipe for hyperscan.
In this scenario, where hyperscan is only consumed as a library, the examples are not used at all, and building them would be wasted power. Whwn only building a single version of hyperscan, that might not be noticiable, but when building multiple versions (different combinations of compilers, build flags, etc) the extra costs sum up.
So it would be nice to have a simple BUILD_EXAMPLES cmake option.

**Comment by xiangwang1** [comment]
Sure, we'll add this option in our next release.

**Comment by Nor7th** [comment]
Added in v5.4.0
