### ISSUE TITLE
Segmentation Fault during run time.

### ISSUE THREAD

**Issue by MousumiBoruah** [intel/hyperscan#263]
I have used two databases in HS_MODE_BLOCK for two different pattern matching. The issue is that whenever I assign scratch space for searching in the second database then there is a segmentation fault. Mainly the issue is with scratch space allocation. But the same program runs well in some other systems like macOS Mojave. 

My functions for database compilation are, I have used db_header and db_payload as databases and scratch_header and scratch_payload as scartch spaces.
void Hyperscan_compile_header(char *file){
	int size = 0;
	size = parseFile(file);
  
	hs_error_t err;
	err = hs_compile_multi(expressions_header,NULL,NULL,size, HS_MODE_BLOCK,NULL, &db_header, &compile_err);
	if (err != HS_SUCCESS){
		printf("Error in hs_compile_multi part--\n");
	}
	if (hs_alloc_scratch(db_header, &scratch_header) != HS_SUCCESS) {
        fprintf(stderr, "ERROR: Unable to allocate scratch space. Exiting.\n");
        hs_free_database(db_header);
        return;
    }
}
void Hyperscan_compile_payload(char *content_file){
	int size = 0;

	size = parseFile_for_payload(content_file);
	hs_error_t err;

	err = hs_compile_multi(expressions_payload,NULL,NULL,size, HS_MODE_BLOCK,NULL, &db_payload, &compile_err_1);
	if (err != HS_SUCCESS){
		printf("Error in hs_compile_multi part\n");
	}
	if (hs_alloc_scratch(db_payload, &scratch_payload) != HS_SUCCESS) {
        fprintf(stderr, "ERROR: Unable to allocate scratch space. Exiting.\n");
        hs_free_database(db_payload);
        return;
    }
}

The issue is with the second scratch space. Please mention if I have done any mistake in doing the same.

void Hyperscan_search_payload(char *inputData){
	int length = strlen(inputData);

	if (!inputData) {
        hs_free_database(db_payload);
        return;
    }
    
    printf("Scanning the payload with Hyperscan\n.\n.\n.\n");

    if (hs_scan(db_payload, inputData, length, 0, scratch_payload, eventHandler_payload,
                pattern) != HS_SUCCESS) {
        fprintf(stderr, "ERROR: Unable to scan input buffer. Exiting.\n");
        hs_free_scratch(scratch_payload);
        //free(inputData);
        hs_free_database(db_payload);
        return;
    }
    return;
}

This is my searching function.

**Comment by xiangwang1** [comment]
Can you provide platform details (CPU, OS, etc)? It'll be good if you can also backtrace to find the line of code that causes segment fault.

**Comment by MousumiBoruah** [comment]
The segmentation fault occurs whenever the program is trying to access scratch_payload.

Platform details - 
1) intel i5 - 7th generation
2) Ubuntu 16.04

The output is attached herewith
(https://user-images.githubusercontent.com/38189142/92357634-cfb38280-f105-11ea-9131-1de9572f11e3.jpeg)

**Comment by xiangwang1** [comment]
- Are you using Hyperscan in a virtual machine? If so, how is the instruction level support (check with lscpu)?
- Can you provide the gdb backtrace info?

**Comment by MousumiBoruah** [comment]
I have tried running the program today and it is working fine. I have not edited a single line.
