### ISSUE TITLE
on ARMv8 cpu No intrinsics found

### ISSUE THREAD

**Issue by GitSoftwareNow** [intel/hyperscan#267]

**Comment by xiangwang1** [comment]
Hyperscan doesn't support ARM CPUs.

**Comment by hulksmaaash** [comment]
FYI @GitSoftwareNow -> https://github.com/intel/hyperscan/issues/197 (see the latest update)

**Comment by echoechoin** [comment]
you can use huawei‘s version: https://github.com/kunpengcompute/hyperscan
