### ISSUE TITLE
Scratch space size in terms of database size

### ISSUE THREAD

**Issue by sohant86** [intel/hyperscan#268]
How much percentage of memory does scratch space take for a given database?
For a given db of 100MB how much variance is expected for scratch space...like 1 to 10 MB?
Any relationship between db size & scratch size is known?

I need to use single pool of memory for all the databases and scratch spaces across multiple threads and need to reuse the same memory to avoid memory allocation/deallocation as much as possible. Hence looking for any info that can help.

**Comment by xiangwang1** [comment]
There's not strict relationship between db and scatch size. 
Based on our internal benchmarking, the scratch space is usually between KB to MB level. In most of the case, it will be below 1MB unless your pattern-set is very large (tens of thousands) and complex.
