### ISSUE TITLE
Line Number

### ISSUE THREAD

**Issue by BiBi-Abc** [intel/hyperscan#273]
I'm using HyperScan to find some text in a file. However, when I display it to the user I would like to show the line number of the text. I was wondering if HyperScan already has a built in way to do this so I don't have to iterate through the entire data.

**Comment by xiangwang1** [comment]
We don't report line numbers, and the user needs to find them based on matching offsets from Hyperscan.

**Comment by BiBi-Abc** [comment]
Ah, ok. Thank you for your reply!
