### ISSUE TITLE
Hyperscan compile error (Performing Test ARCH_64_BIT - Failed)

### ISSUE THREAD

**Issue by lpstelma** [intel/hyperscan#283]
I am trying to compile hyperscan for snort on Raspberry Pi:

OS: Ubuntu 20.10 aarch64            
Host: Raspberry Pi 4 Model B Rev 1.4
Kernel: 5.8.0-1007-raspi            

The problem came up when using **g++ version 10.2.0,  cmake version 3.16.3, boost1.72.0, and hyperscan 5.2.1**:

> pi0@pi0-desktop:~/snort_src/hyperscan-5.2.1-build$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBOOST_ROO
> T=~/snort_src/boost_1_72_0/ ../hyperscan-5.2.1                                                        
>                                                                                                       
> -- The C compiler identification is GNU 10.2.0                                                        
> -- The CXX compiler identification is GNU 10.2.0                                                      
> -- Check for working C compiler: /usr/bin/cc                                                          
> -- Check for working C compiler: /usr/bin/cc -- works                                                 
> -- Detecting C compiler ABI info                                                                      
> -- Detecting C compiler ABI info - done                                                               
> -- Detecting C compile features                                                                       
> -- Detecting C compile features - done                                                                
> -- Check for working CXX compiler: /usr/bin/c++                                                       
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
**> -- Performing Test ARCH_64_BIT
> -- Performing Test ARCH_64_BIT - Failed
> -- Performing Test ARCH_32_BIT
> -- Performing Test ARCH_32_BIT - Failed**
> -- Default build type 'Release with debug info'
> -- using release build
> -- Boost version: 1.72.0
> -- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
> -- Build date: 2020-11-12 
> -- Building static libraries
> -- gcc version 10.2.0
> CMake Error at CMakeLists.txt:202 (message):
>   Something went wrong determining gcc tune: -mtune=armv8-a+crc not valid
> 
> 
> -- g++ version 10.2.0
> -- Looking for include file unistd.h
> -- Looking for include file unistd.h - found
> -- Looking for include file intrin.h
> -- Looking for include file intrin.h - not found
> -- Looking for C++ include intrin.h
> -- Looking for C++ include intrin.h - not found
> -- Looking for include file x86intrin.h
> -- Looking for include file x86intrin.h - not found 
> -- Looking for C++ include x86intrin.h
> -- Looking for C++ include x86intrin.h - not found
> -- Looking for posix_memalign
> -- Looking for posix_memalign - found
> -- Looking for _aligned_malloc
> -- Looking for _aligned_malloc - not found
> -- Performing Test HAS_C_HIDDEN
> -- Performing Test HAS_C_HIDDEN - Success
> -- Performing Test HAS_CXX_HIDDEN
> -- Performing Test HAS_CXX_HIDDEN - Success
> -- Looking for _LIBCPP_VERSION
> -- Looking for _LIBCPP_VERSION - not found
> -- generator is Unix Makefiles
> -- Performing Test HAS_C_ATTR_IFUNC
> -- Performing Test HAS_C_ATTR_IFUNC - Success
> CMake Error at cmake/arch.cmake:10 (message):
>   No intrinsics header found
> Call Stack (most recent call first):
>   CMakeLists.txt:332 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi0/snort_src/hyperscan-5.2.1-build/CMakeFiles/CMakeOutput.log".
> See also "/home/pi0/snort_src/hyperscan-5.2.1-build/CMakeFiles/CMakeError.log".

[CMakeOutput.log](https://github.com/intel/hyperscan/files/5534677/CMakeOutput.log)
[CMakeError.log](https://github.com/intel/hyperscan/files/5534683/CMakeError.log)

**I found a somewhat similar error from 2018 recomending a patch of changing distance to std::distance in the 'snort_src/hyperscan-5.2.1/src/nfa/limex_compile.cpp' file [here](https://github.com/intel/hyperscan/issues/104).**
I checked to make sure this was patched in the version I am running and it is:

> static                                                                  
> u32 addSquashMask(const build_info &args, const NFAVertex &v,           
>                   vector<NFAStateSet> &squash) {                        
>     auto sit = args.reportSquashMap.find(v);                            
>     if (sit == args.reportSquashMap.end()) {                            
>         return MO_INVALID_IDX;                                          
>     }                                                                   
>                                                                         
>     // This state has a squash mask. Paw through the existing vector to 
>     // see if we've already seen it, otherwise add a new one.           
>     auto it = find(squash.begin(), squash.end(), sit->second);          
>     if (it != squash.end()) {                                           
>         return verify_u32(std::distance(squash.begin(), it));           
>     }                                                                   
>     u32 idx = verify_u32(squash.size());                                
>     squash.push_back(sit->second);                                      
>     return idx;                                                         
> }                                                                       
>                                                                         
> using ReportListCache = ue2_unordered_map<vector<ReportID>, u32>;       
>                                                                         
> static                                                                  
> u32 addReports(const flat_set<ReportID> &r, vector<ReportID> &reports,  
>                ReportListCache &reports_cache) {                        
>     assert(!r.empty());                                              
>                                                                      
>     vector<ReportID> my_reports(begin(r), end(r));                   
>     my_reports.push_back(MO_INVALID_IDX); // sentinel                
>                                                                      
>     auto cache_it = reports_cache.find(my_reports);                  
>     if (cache_it != end(reports_cache)) {                            
>         u32 offset = cache_it->second;                               
>         DEBUG_PRINTF("reusing cached report list at %u\n", offset);  
>         return offset;                                               
>     }                                                                
>                                                                      
>     auto it = search(begin(reports), end(reports), begin(my_reports),
>                      end(my_reports));                               
>     if (it != end(reports)) {                                        
>         u32 offset = verify_u32(std::distance(begin(reports), it));  
>         DEBUG_PRINTF("reusing found report list at %u\n", offset);   
>         return offset;                                               
>     }                                                                
>                                                                      
>     u32 offset = verify_u32(reports.size());                         
>     insert(&reports, reports.end(), my_reports);                     
>     reports_cache.emplace(move(my_reports), offset);                 
>     return offset;                                                   
> }

                                                                    

Any clues as to what this could be would be appreciated.

**Comment by xiangwang1** [comment]
According to this CMake output `Something went wrong determining gcc tune: -mtune=armv8-a+crc not valid`, sounds like you are running on ARM platform. 
Hyperscan supports x86 platforms only.

**Comment by lpstelma** [comment]
I found [this](https://github.com/kunpengcompute/hyperscan) https://github.com/kunpengcompute/hyperscan which supports aarch64 and was able to install and make sure it works:
cd ~/snort_src
wget https://github.com/kunpengcompute/hyperscan/archive/v5.2.1.aarch64.tar.gz
tar -xvzf v5.2.1.aarch64.tar.gz

mkdir ~/snort_src/hyperscan-5.2.1-build
cd hyperscan-5.2.1-build/

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBOOST_ROOT=~/snort_src/boost_1_72_0/ ../hyperscan-5.2.1.aarch64

make
sudo make install

cd ~/snort_src/hyperscan-5.2.1-build/
./bin/unit-hyperscan
