### ISSUE TITLE
hs_compile_ext_multi() core dump

### ISSUE THREAD

**Issue by I0-0I-gqj** [intel/hyperscan#284]
Hi: 
   When i use "hs_set_allocator" with dpdk "rte_malloc" "rte_free", then use  "hs_compile_ext_multi" happened core dump.
  I find in src\parser\logical_combination.cpp function validateSubIDs() :154 : free(info); info is free by "free", but malloc by "hs_misc_alloc", in hs.cpp:577; why not use "hs_misc_free" ?

**Comment by xiangwang1** [comment]
Yes, it should be. Will changing it to `hs_misc_free` address your issue?

**Comment by I0-0I-gqj** [comment]
> Yes, it should be. Will changing it to `hs_misc_free` address your issue?

Yes, I changing it to "hs_misc_free" address my issue.
But, I found another issue: i use "hs_set_allocator" and no use "ch_set_allocator", "ch_compile_multi" will core dump also by "free". when i use "hs_set_allocator" and "ch_set_allocator", it is ok.  
My c++ is bad. So, I can not found reason.

**Comment by Nor7th** [comment]
Fixed in v5.4.0
