### ISSUE TITLE
Questions about lack of ordering

### ISSUE THREAD

**Issue by zlx19950903** [intel/hyperscan#289]
What is the meaning of lack of ordering? Will the latter match occurs before the former one? And what makes it happen?

**Comment by xiangwang1** [comment]
Yes, there could be cases that matching offsets are delivered out of order.

This could be related to zero width assertions such as word boundary `\b`, end of match `\z`, etc.
For example, a zero width assertion at offset 100 cannot be reported until at offset 101 in the case that it requires us to know that offset 101 is a word or non-word or \n character. 

Unless something clever is done, you may run after some other matching engine within Hyperscan that delivers a true match at 101 and you will wake up and say "oh, I just learned we had a match at 100".
 
In general, it will be **_hard_** to make this out of order behavior happen under most cases as we have many mechanisms to hide it.

**Comment by zlx19950903** [comment]
> Yes, there could be cases that matching offsets are delivered out of order.
> 
> This could be related to zero width assertions such as word boundary `\b`, end of match `\z`, etc.
> For example, a zero width assertion at offset 100 cannot be reported until at offset 101 in the case that it requires us to know that offset 101 is a word or non-word or \n character.
> 
> Unless something clever is done, you may run after some other matching engine within Hyperscan that delivers a true match at 101 and you will wake up and say "oh, I just learned we had a match at 100".
> 
> In general, it will be **_hard_** to make this out of order behavior happen under most cases as we have many mechanisms to hide it.

Thanks a lot!
