### ISSUE TITLE
Question about non-greedy mode

### ISSUE THREAD

**Issue by zlx19950903** [intel/hyperscan#290]
Hi! I have a regex "<.*?>" and a sentence "<html>content</html>", the answer will be "<html>" and "<html>content</html>" duoeto the default greedy mode. But if I also want to get "</html>", what should I do?

**Comment by xiangwang1** [comment]
Hyperscan doesn't support greedy and ungreedy modes but report all possible matches. Please refer to our developer's documents at http://intel.github.io/hyperscan/dev-reference/compilation.html#semantics
