### ISSUE TITLE
Unrecognised flag exception for HS_FLAG_COMBINATION in ParsedExpression::ParsedExpression

### ISSUE THREAD

**Issue by foxever** [intel/hyperscan#291]
HS_FLAG_ALL is not include all valid hyperscan flags, which may cause flags check failed, eg 

https://github.com/intel/hyperscan/blob/c00683d73916e39f01b0d418f686c8b5c379159c/src/hs_internal.h#L75-L84

eg, flag `HS_FLAG_COMBINATION` failed to pass check and throw an `Unrecognised flag` exception
https://github.com/intel/hyperscan/blob/c00683d73916e39f01b0d418f686c8b5c379159c/src/compiler/compiler.cpp#L180-L183

**Comment by fatchanghao** [comment]
I think this failure won't happen, actually HS_FLAG_COMBINATION is not a Regex flag, and in function addExpression() the logical expression will be bypassed (line 286-323) before constructing a ParsedExpression object (line 332), so in ParsedExpression constructor it should only check Regex flags.
Did you meet a case that ran into this problem?

**Comment by foxever** [comment]
> I think this failure won't happen, actually HS_FLAG_COMBINATION is not a Regex flag, and in function addExpression() the logical expression will be bypassed (line 286-323) before constructing a ParsedExpression object (line 332), so in ParsedExpression constructor it should only check Regex flags.
> Did you meet a case that ran into this problem?

more specifically, **hs_expression_info(..., HS_FLAG_COMBINATION ...)** -> **hs_expression_info_int** -> **ParsedExpression ctor**

int the doc  [hs_expression_info](https://intel.github.io/hyperscan/dev-reference/api_files.html#c.hs_expression_info), HS_FLAG_COMBINATION is a valid flag to call hs_expression_info. is this a valid usage for this api?

**Comment by fatchanghao** [comment]
> > I think this failure won't happen, actually HS_FLAG_COMBINATION is not a Regex flag, and in function addExpression() the logical expression will be bypassed (line 286-323) before constructing a ParsedExpression object (line 332), so in ParsedExpression constructor it should only check Regex flags.
> > Did you meet a case that ran into this problem?
> 
> more specifically, **hs_expression_info(..., HS_FLAG_COMBINATION ...)** -> **hs_expression_info_int** -> **ParsedExpression ctor**
> 
> in the doc [hs_expression_info](https://intel.github.io/hyperscan/dev-reference/api_files.html#c.hs_expression_info), HS_FLAG_COMBINATION is a valid flag to call hs_expression_info. is this a valid usage for this api?

This API should also bypass HS_FLAG_COMBINATION, we will fix it, thanks for reporting!
