### ISSUE TITLE
CMake Error at cmake/boost.cmake:23 (message):

### ISSUE THREAD

**Issue by 1170300913** [intel/hyperscan#295]
Boost 1.57.0 or later not found.  Either install system packages if
  available, extract Boost headers to /home/tth/hyperscan/include, or set the
  CMake BOOST_ROOT variable.
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)

-- Configuring incomplete, errors occurred!
See also "/home/tth/hs_build/CMakeFiles/CMakeOutput.log".
See also "/home/tth/hs_build/CMakeFiles/CMakeError.log".

**Comment by 1170300913** [comment]
When I type “cmake ../hyperscan”，such a problem encountered. Can you help me?

**Comment by xiangwang1** [comment]
Have you installed boost library? If not, please check our library dependency at http://intel.github.io/hyperscan/dev-reference/getting_started.html#requirements

**Comment by 1170300913** [comment]
Thank you very much! I have solved this problem.&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel/hyperscan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午4:03
收件人:&nbsp;"intel/hyperscan"<hyperscan@noreply.github.com&gt;;
抄送:&nbsp;"1034123425"<1034123425@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [intel/hyperscan] CMake Error at cmake/boost.cmake:23 (message): (#295)





 
Have you installed boost library? If not, please check our library dependency at http://intel.github.io/hyperscan/dev-reference/getting_started.html#requirements
