### ISSUE TITLE
Failed to build expressionutil

### ISSUE THREAD

**Issue by artemtsai** [intel/hyperscan#296]
Failed to build expressionutil project.
OS: Win10x64
VS Studio 2017
Boost 1_75_0

`C:\Workspace\filehive\workenv\hyperscan\build\util\ExpressionParser.cpp(108): error C2065: 'ExpressionParser_error': undeclared identifier [C:\Workspace\filehive\workenv\hyperscan\build\util\expressionutil.vcxproj]`

**Comment by cicaglisa80** [comment]
Same problem for me... 
Did you manage to fix this error?

**Comment by cicaglisa80** [comment]
Found the problem. In my case gcc compiler was missing and also ragel wasn't installed. Once I did those 2 changes it managed to build it.
