### ISSUE TITLE
performance problems 

### ISSUE THREAD

**Issue by jeskon666** [intel/hyperscan#297]
why in the doc you say: Under all circumstances it is better to use longer literals than shorter ones ?
问一下为啥短的性能差？

**Comment by daveMmd** [comment]
You can refer the paper https://www.usenix.org/system/files/nsdi19-wang-xiang.pdf. 

In short, short text is more likely to be matched. Therefore, the performance is poor.

**Comment by jeskon666** [comment]
thank u
