### ISSUE TITLE
Add expression index argument to hsbench

### ISSUE THREAD

**Issue by sbates130272** [intel/hyperscan#298]
It would be useful if hsbench could take an input argument listing which expressions in the expression file to compile and search for. This would allow for easier performance vs expression count benchmarking. For example:

```
hsbench -P 1-10 -T 0-7 -n 1000 -e pcre/teakettle_2500 -c corpora/gutenberg.db
```
would only match against the patterns labelled 1 through 10. I'd be happy to work on this (or assign someone on my team ;-)) if there is an interest in upstreaming this feature.

**Comment by Nor7th** [comment]
Will the `-s` argument of hsbench be help?

`-s FILE : Signature file to use.`

Users can assign specific expression index in the signature file to control which set of expressions they want to match.

For example, given rule.txt:
```
0:/aa/
1:/bb/
2:/cc/
3:/dd/
```

Signature file sigs.txt can be:
```
0
2
```

or
```
1
2
3
```

So just use `hsbench -e rule.txt -s sigs.txt -c ...` to achieve your goal.

However, signature file needs to list all the indexes each time you want.

**Comment by fatchanghao** [comment]
"-s" option can solve your problem, as described above, close it now.
