### ISSUE TITLE
Crash in hs_scan avx2 on CentOS 7 server

### ISSUE THREAD

**Issue by sohant86** [intel/hyperscan#299]
Hello Team,

I have built hyperscan 5.3.0 on CentOS 7.9 and running the application on CentOS 7.3
Please find below crash details & lscpu of build machine & application server.
Let me know what could have gone wrong.

***** CRASH GDB OUTPUT*****
(gdb) bt
#0  0x00007ffe6d7186f5 in avx2_shuftiExec () from /usr/local/lib64/libhs.so
#1  0x00007ffe6d68ded9 in avx2_run_accel () from /usr/local/lib64/libhs.so
#2  0x00007ffe6d6a46d2 in goughExec8_i_ni () from /usr/local/lib64/libhs.so
#3  0x00007ffe6d6a600b in avx2_nfaExecGough8_QR () from /usr/local/lib64/libhs.so
#4  0x00007ffe6d746ec0 in avx2_roseRunProgram () from /usr/local/lib64/libhs.so
#5  0x00007ffe6d73fba5 in avx2_roseFloatingCallback () from /usr/local/lib64/libhs.so
#6  0x00007ffe6d791b71 in avx2_fdr_exec_fat_teddy_msks4_pck () from /usr/local/lib64/libhs.so
#7  0x00007ffe6d65c0b2 in avx2_fdrExec () from /usr/local/lib64/libhs.so
#8  0x00007ffe6d727000 in avx2_roseBlockExec () from /usr/local/lib64/libhs.so
#9  0x00007ffe6d64b00e in avx2_hs_scan () from /usr/local/lib64/libhs.so
#10 0x0000000000e95809 in custom_pattern_search ()

******* Hyperscan 5.3.0 build machine - CentOS 7.9 ******
hyperscan-5.3.0]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz
Stepping:              4
CPU MHz:               1995.312
BogoMIPS:              3990.62
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec arat pku ospke spec_ctrl intel_stibp flush_l1d arch_capabilities

******************Application Server - CentOS 7.3****************
[root@localhost bin]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                88
On-line CPU(s) list:   0-87
Thread(s) per core:    2
Core(s) per socket:    22
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2772.399
CPU max MHz:           3700.0000
CPU min MHz:           1000.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              30976K
NUMA node0 CPU(s):     0-21,44-65
NUMA node1 CPU(s):     22-43,66-87
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear spec_ctrl intel_stibp flush_l1d

**Comment by xiangwang1** [comment]
Can you provide the patterns and corpus to reproduce this issue?

**Comment by sohant86** [comment]
Let me collect patterns and input data and update you in sometime.

**Comment by sohant86** [comment]
Application issue - Passing same scratch context for multiple threads, fixed it.
