### ISSUE TITLE
Hyperscan with nDPI

### ISSUE THREAD

**Issue by utkarsh0902311047** [intel/hyperscan#300]
Hi, I am using Centos7.
I have downloaded hyperscan and nDPI.
I want to use hyperscan for the packets captured but don't know what command should I write.
I also want to use it with nDPI.
Please, someone, suggest to me what steps can I do
Thank you

**Comment by xiangwang1** [comment]
To use nDPI with Hyperscan, you need 
1. Choose a nDPI release between 2.2.2 and 3.2
2. Turn on `--with-hyperscan` when configure nDPI
