### ISSUE TITLE
Are libhs.a so large?

### ISSUE THREAD

**Issue by utszcrystal** [intel/hyperscan#308]
I compile hyperscan, and output libhus.a , it is 500M, how I can trim it?

**Comment by amno1** [comment]
I can confirm that libhs.a is huge, on my system ~340 meg. I odn't have avx2, I guess it would be even bigger if I had those? :-)

± |master U:1 ?:1 ✗| → ls bin -hs
totalt 1,8G
251M hsbench  249M hscheck  259M hscollider  249M patbench  248M pcapscan  248M simplegrep  278M unit-hyperscan

 2021-03-25 23:38:11 ⌚  pascal in ~/repos/hyperscan/build
± |master U:1 ?:1 ✗| → ls lib -hs
totalt 416M
5,0M libcorpusomatic.a  184K libcrosscompileutil.a   96K libdatabaseutil.a  620K libexpressionutil.a  342M libhs.a   69M libhs_runtime.a

C++? Entire Boost + STDLIB? :-).

**Comment by xiangwang1** [comment]
There's no good way to trim it as all functionalities are required. 

Yes, fat runtime is on by default - you can specify `-march` option for CMake to only build a single version of runtime binary (http://intel.github.io/hyperscan/dev-reference/getting_started.html#target-architecture).

**Comment by delins** [comment]
I came across this question looking for cmake related tickets, sorry for necromancing. But I think the given answer misses the point.

@utszcrystal & @amno1 you probably built hyperscan in RelWithDebInfo mode, or plain Debug (default is RelWithDebInfo). This will result in those large binaries you see. If you build it in Release mode the binaries should be around 4MB and 8MB. There's some info on the build types [here](http://intel.github.io/hyperscan/dev-reference/getting_started.html#cmake-configuration)

**Comment by amno1** [comment]
Thanks Delins. The author answered just my question about fat runtime, but yes your answer gives more details. Of course Release version will be smaller then Debug version. I just thought that even for a debug version ~500 meg for a library is a bit much :-).

On my comp (Arch Linux on i7-6700K with march=native and in Release mode, no fat runtime, size is ~16meg for the static lib and ~ 5.1 meg for the static runtime.

**Comment by delins** [comment]
Ah ok. Yeah it's rather sizeable :)
