### ISSUE TITLE
Modify hs_scan_vector to utilize size_t instead of 'unsigned int' as size_t is more appropriate array size type. 

### ISSUE THREAD

**Issue by Ludio** [intel/hyperscan#310]
Implementing C++ wrappers or simply working with large data sets it would seem that utilizing size_t would be a better option. As an example hs_compile_lit_multi currently uses size_t and is similar in behavior to hs_scan_vector. 

**Existing Function:**

hs_error_t hs_scan_vector(const hs_database *db, const char * const *data, const unsigned int *length, unsigned int count, unsigned int flags, hs_scratch *scratch, match_event_handler onEvent, void *context);

**Proposed Alternative:**

hs_error_t hs_scan_vector(const hs_database *db, const char * const *data, const size_t *length, size_t count, unsigned int flags, hs_scratch *scratch, match_event_handler onEvent, void *context);

**Comment by delins** [comment]
I can't give an authoritative answer, but I asked a similar question in #118. The gist of the answer is that hyperscan uses 32 bit types internally, it would require a lot of work to change it all to 64, and there were no plans to do so back then. But you can use vector/stream mode to overcome the `unsigned int` limitation in case you want to scan >4GB files.

**Comment by fatchanghao** [comment]
we don't have such plan.
