### ISSUE TITLE
Obtaining the worst-case running time of a Regex expression

### ISSUE THREAD

**Issue by Olament** [intel/hyperscan#314]
Hi,

We are currently working on a performance sensitive application and we would like to evaluate the performance of Hyperscan under different scenario. Is there any existing tool to obtain the worst-case running time for a given Regex expression? 

Thanks!

**Comment by xiangwang1** [comment]
There's no tool to get worst-case performance. You can try our tool "hsbench" to test Hyperscan performance under different realistic rules and corpora.

In general, PCRE or other libs with backtracking approach can cause worst exponential runtime cost and risk of DoS, but Hyperscan guarantees this won't happen.

**Comment by Olament** [comment]
@xiangwang1 Thanks for the reply.

I am aware of the existence of "hsbench" but It can only evaluate the performance of Hyperscan against a given regular expression and input strings. Our goal is to find the input string that results a worst-case running time for a given regular expression.

Also, If I am understanding the NSDI paper correctly, the worst-case running time happens when the input string passed the string literal pre-filtering and the regular expression is too complex to generate a DFA representation such that Hyperscan engine falls back to NFA. Is that correct? Also, I am wondering what is going to happen if the NFA has more than 512 states such that It cannot be fit into a 512-bit mask?

Thanks

**Comment by xiangwang1** [comment]
@Olament 
Yes, that's very hard to do and no existing tool support for it.

Yes, the worst case is failed literal prefiltering for all literal components and triggering of all engine(NFA, DFA, etc) components within a single rule. Hyperscan compiler will conduct further decomposition if a subgraph can't be transformed to both DFA and NFA representations.

**Comment by Olament** [comment]
Got it. Thank you!
