### ISSUE TITLE
hs_compile/hs_compile_multi: Allocation failures in ue2::AlignedAllocator can cause segfaults

### ISSUE THREAD

**Issue by johanngan** [intel/hyperscan#317]
I work on a system with embedded Hyperscan where reliability is extremely important, and we've encountered unexpected segfaults when calling `hs_compile_multi` in a low-memory environment. Given that [`hs_compile_multi_int` will usually catch `std::bad_alloc`](https://github.com/intel/hyperscan/blob/64a995bf445d86b74eb0f375624ffc85682eadfe/src/hs.cpp#L272) when an allocation fails and respond with `HS_COMPILER_ERROR`, crashes from `hs_compile` and `hs_compile_multi` seem like unintended behavior.

The root cause seems to be an issue with [`ue2::AlignedAllocator::allocate()`](https://github.com/intel/hyperscan/blob/master/src/util/alloc.h#L79), which is used as a [custom allocator for `std::vector` when building the the `RoseEngineBlob`](https://github.com/intel/hyperscan/blob/master/src/rose/rose_build_engine_blob.h#L171). [C++ allocators are expected to raise `std::bad_alloc` on failure](https://stackoverflow.com/questions/50326564/should-c-allocatorallocate-throw-or-return-nullptr-when-allocation-fails), but `AlignedAllocator::allocate()` is backed by [`aligned_malloc_internal()`](https://github.com/intel/hyperscan/blob/master/src/util/alloc.cpp#L62), which returns `nullptr` on failure. The standard library appears to assume validity of the return value of `allocator::allocate()` (at least, `libstdc++` does), hence the segmentation fault.

All the crashes I've seen have come from calls to `std::vector::resize()` like [this one](https://github.com/intel/hyperscan/blob/master/src/rose/rose_build_engine_blob.h#L88). Here's a trimmed example stack trace (I can provide more detailed stack traces if need be):

1. `std::vector<char, ue2::AlignedAllocator<char, 64ul> >::resize`
2. `ue2::RoseEngineBlob::add`
3. `ue2::RoseBuildImpl::buildFinalEngine`
4. `ue2::RoseBuildImpl::buildRose`
5. `ue2::generateRoseEngine`
6. `hs_compile_multi`

The most obvious solution would be to throw `std::bad_alloc` in `AlignedAllocator::allocate()` rather than returning `nullptr`. I've been able to reproduce the segfault, and with this change the crash seems to go away (if a patch would be helpful, I can try to throw one together). I haven't checked if this handles all the necessary cleanup, though.

## Additional info

- Hyperscan version: initial crash was on 5.3.0, but I've been able to repro this after building 5.4.0 (current `master` head) as well.
- Platform: Gentoo Linux (kernel: 4.15.0-128-generic)
- Repro steps: Apologies for not providing a reproducible test case here. The one I used myself involves a proprietary database, and I suspect this might be highly platform-dependent anyway (but if it would be helpful, I can try to construct a test case). To describe what I did to reproduce this on my machine, I wrote a dummy program that:
  1. Limits the process address space with `setrlimit(2)`. I had to tune the heap limit to get it to crash, since Hyperscan already catches _most_ allocation failures. Memory has to run out at _just_ the right point, when `hs_compile_multi_int` is building the rose engine blob.
  2. Runs `hs_compile_multi` with a fairly large set of expressions.
  3. Causes a SIGSEGV.

**Comment by xiangwang1** [comment]
@johanngan, thanks for all these details.

This is a hard to reproduce case requiring certain preconditions (rules, platform, memory resource, etc).  
It makes sense to me as our customized `aligned allocator` should expose consistent behavior with the [default one](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/libsupc%2B%2B/new_op.cc) in C++ which throws `std:bad_alloc`.

Can you create a pull request? It'll be also great if you can share a test case with us if possible.

**Comment by johanngan** [comment]
@xiangwang1 Created https://github.com/intel/hyperscan/pull/320. I double-checked that just throwing wouldn't cause any leaks, and I believe everything is properly handled by destructors. [The same thing is done later on in `buildFinalEngine`](https://github.com/intel/hyperscan/blob/master/src/rose/rose_build_bytecode.cpp#L3874), after all.

Upon further thought, I fear it might not be possible to provide a realistic, platform-independent test case, because the crash depends on the details of how the kernel allocates memory. But I made a second [throwaway branch](https://github.com/johanngan/hyperscan/tree/allocation-failure-segfault-repro) that simulates OOM by forcing `AlignedAllocator::allocate()` to always return `nullptr`; haven't actually tested it yet, but I think if you build `libhs` from that branch it should reproduce the SIGSEGV.

**Comment by hongyang7** [comment]
Thanks for the PR, we're considering it for next release.

And another interesting thing to share:
The [aligned_zmalloc](https://github.com/intel/hyperscan/blob/64a995bf445d86b74eb0f375624ffc85682eadfe/src/util/alloc.cpp#L100) defined in the same file also invoke aligned_malloc_internal, but adds a "throw std:bad_alloc" step for upper invoker. However, this func is only used in our internal tests. We just missed this potential risk. Thanks again.

**Comment by hongyang7** [comment]
Please refer to latest develop branch.
