### ISSUE TITLE
Don't understand what HS_FLAG_ALLOWEMPTY is good for

### ISSUE THREAD

**Issue by elmart-devo** [intel/hyperscan#323]
Hi. I've read available documentation and made a handful of tests on the behaviour of `HS_FLAG_ALLOWEMPTY` flag. My tests are using the pattern `a?`.

If I understand correctly, any scan using that flag would produce a match on every position of the scanned string (byte positions if UTF8 flag is not used, unicode point start positions if UTF8 flag is used). But then, how can I distinguish the case when the "a" is effectively there?

I thought I could do that using the additional flag `HS_FLAG_SOM_LEFTMOST`, but combination of both flags is not supported.

Then, my question is: given that a scan using `HS_FLAG_ALLOWEMPTY`will allways match at every position, and I have no way to distinguish an empty match from a non-empty one, what's the flag purpose? I mean, the answer doesn't seem to have any information about matches.

Am I misunderstanding anything???

**Comment by xiangwang1** [comment]
The pattern and flags are defined based on user's intention. Users may 1) only want to know if there are matches, 2) care about empty matches, 3) want to distinguish empty from non-empty matches, etc. It's up to users to make the choice.
This empty flag is based on a similar PCRE definition.

In your case of distinguishing empty from non-empty matches, you could already know all empty matches even before the scan for your pattern `a?`. The only thing to find is actually non-empty matches by not having `HS_FLAG_ALLOWEMPTY`.

**Comment by elmart-devo** [comment]
Thanks, I understand what you say, about flags being defined based on users' intention.
But I still can't find any useful usage for this flag. Could you please show one example where this flag actually does something meaningful?
