### ISSUE TITLE
$ always matches newline regardless of HS_FLAG_MULTILINE flag

### ISSUE THREAD

**Issue by kaizawa** [intel/hyperscan#324]
Hi 

I expected the pattern "^foo$" never match "foo\n", but actually it always matches regardless of HS_FLAG_MULTILINE.
This can be checked by appending the following code to the unit\internal\nfagraph_find_matches.cpp

```
static const MatchesTestParams matchesTests[] = {
... 
    {"^foo$", "foo\n", {},0 , false, true},
...
```
In the API documentation of HS_FLAG_MULTILINE, the following explanation is found. I think $ should work as described here.

```
If this flag is not specified, the ^ token will only ever match at the start of a stream,
 and the $ token will only ever match at the end of a stream within the guidelines of 
the PCRE specification.
```

* Using \z instead of $ 
* 
* be a workaround.

I'm using hyperscan version 5.4.0.

Thanks,
Kazuyoshi

**Comment by xiangwang1** [comment]
Hyperscan complies with PCRE syntax definitions. You can refer to the PCRE document at https://www.pcre.org/original/pcre.txt: 


ANCHORS AND SIMPLE ASSERTIONS:

         ^           start of subject
                      also after internal newline in multiline mode
         \A          start of subject
         $           end of subject
                      also before newline at end of subject
                      also before internal newline in multiline mode
         \Z          end of subject
                      also before newline at end of subject
         \z          end of subject
         \G          first matching position in subject

`$` matches `before newline at the end of subject`, which exposes different behavior from `\z`

**Comment by kaizawa** [comment]
Hi Xiang,

Thank you! I understand it's an exepected behavior. 

Kauzyoshi
