### ISSUE TITLE
HS_FLAG_COMBINATION logical error

### ISSUE THREAD

**Issue by arshfalanor3** [intel/hyperscan#325]
id 1 is ture , id 2 is ture , why combination for (!1)|(!2) is true?

**Comment by variar** [comment]
Could it be that there is an offset in the search data where id1 or id2 is false?

**Comment by arshfalanor3** [comment]
> Could it be that there is an offset in the search data where id1 or id2 is false?

just test：search data："vvvabcvvvdef",  id 1 for search "abc", id 2 for search "def", id 3 is combination (!1)|(!2) ,but  id 3 matched. use mode HS_MODE_BLOCK

**Comment by xiangwang1** [comment]
The matching result of logical combination is offset based. 
So for each individual offset of your search data, we will evaluate whether `abc` and `def` have matched. We will report matches at at offsets where not both of them have matched.

**Comment by arshfalanor3** [comment]
> The matching result of logical combination is offset based.
> So for each individual offset of your search data, we will evaluate whether `abc` and `def` have matched. We will report matches at at offsets where not both of them have matched.

I see. thank you
