### ISSUE TITLE
Can't build anything on OSX

### ISSUE THREAD

**Issue by mewalig** [intel/hyperscan#338]
Hi,

This library looks great-- thank you. I'd love to use it. Is there any current documentation anywhere that describes how to build on OSX?

I've made several tries now but have been unable to get any component to compile-- from the start, the cmake command always fails. For example, the following commands:
```
mkdir build && cd build && cmake ..
```

fail with one of the two log files ending with:
```
Linking C executable cmTC_71e13
/usr/local/Cellar/cmake/3.19.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_71e13.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_71e13.dir/src.c.o -o cmTC_71e13


Source file was:
#if !(defined(__x86_64__) || defined(_M_X64))
#error not 64bit
#endif
int main(void) { return 0; }
```

On the topic of OSes in general: are Windows, OSX and web assembly all targets that this library is expected to be able to run on?

Thank you in advance for your assistance

**Comment by hulksmaaash** [comment]
If you're running on an M1, you may want to check out this version -> https://github.com/VectorCamp/vectorscan

**Comment by liquidaty** [comment]
Working on OSX (non-M1) now, at least with `-DFAT_RUNTIME=off`
