### ISSUE TITLE
failed to build on fedora 35

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [intel/hyperscan#339]
[100%] Linking CXX executable ../bin/unit-hyperscan
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `core2_memcpy'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `core2_memmove'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `avx2_memmove'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `corei7_snprintf'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `core2_snprintf'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `avx2_snprintf'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `corei7_memcpy'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.so.5.4.0: undefined reference to `corei7_memmove'

**Comment by zhuizhuhaomeng** [comment]
@jviiret can you help with this?

**Comment by jmtaylor90** [comment]
Which version of hyperscan are you trying to build? Hyperscan 5.4.0 is currently available in Fedora, https://koji.fedoraproject.org/koji/buildinfo?buildID=1817314

**Comment by zhuizhuhaomeng** [comment]
thanks a lot. There is a patch https://src.fedoraproject.org/rpms/hyperscan/blob/rawhide/f/hyperscan-5.4.0-build_wrapper_fix.patch
