### ISSUE TITLE
Bad performance for space character 

### ISSUE THREAD

**Issue by pengtianabc** [intel/hyperscan#346]
Hi everyone!

I got a bad performance issue for space character when hsbench testing.

bad performance log:
```
[pengtian@localhost build_debug]$ cat test3.pat
4402:/abcdefgh/sH
4425:/[a-zA-Z]( |\x26)/sH

[pengtian@localhost build_debug]$ bin/hsbench -c corpora/gutenberg.db -e test3.pat

WARNING: DO NOT BENCHMARK A HYPERSCAN BUILD WITH ASSERTIONS

Signatures:        test3.pat
Hyperscan info:    Version: 5.4.0 Features:  Mode: STREAM
Expression count:  2
Bytecode size:     5,032 bytes
Database CRC:      0xf6c40393
Stream state size: 26 bytes
Scratch size:      2,317 bytes
Compile time:      0.001 seconds
Peak heap usage:   9,732,096 bytes

Time spent scanning:       0.990 seconds
Corpus size:               6,701,044 bytes (3,280 blocks in 653 streams)
Matches per iteration:     653 (0.100 matches/kilobyte)
Overall block rate:        66,264.03 blocks/sec
Mean throughput (overall): 1,083.02 Mbit/sec
Max throughput (per core): 1,086.81 Mbit/sec


```

Then i try to change space to tab char, and it's 28x faster than space char
```
[pengtian@localhost build_debug]$ cat test4.pat
4402:/abcdefgh/sH
4425:/[a-zA-Z](\t|\x26)/sH

[pengtian@localhost build_debug]$ bin/hsbench -c corpora/gutenberg.db -e test4.pat

WARNING: DO NOT BENCHMARK A HYPERSCAN BUILD WITH ASSERTIONS

Signatures:        test4.pat
Hyperscan info:    Version: 5.4.0 Features:  Mode: STREAM
Expression count:  2
Bytecode size:     5,032 bytes
Database CRC:      0xe6342004
Stream state size: 26 bytes
Scratch size:      2,317 bytes
Compile time:      0.001 seconds
Peak heap usage:   9,732,096 bytes

Time spent scanning:       0.038 seconds
Corpus size:               6,701,044 bytes (3,280 blocks in 653 streams)
Matches per iteration:     2 (0.000 matches/kilobyte)
Overall block rate:        1,735,767.68 blocks/sec
Mean throughput (overall): 28,369.40 Mbit/sec
Max throughput (per core): 29,558.76 Mbit/sec

```

I also have tried to test the single pattern, still fast:
```
[pengtian@localhost build_debug]$ cat test5.pat
4425:/[a-zA-Z]( |\x26)/sH
[pengtian@localhost build_debug]$ bin/hsbench -c corpora/gutenberg.db -e test5.pat

WARNING: DO NOT BENCHMARK A HYPERSCAN BUILD WITH ASSERTIONS

Signatures:        test5.pat
Hyperscan info:    Version: 5.4.0 Features:  Mode: STREAM
Expression count:  1
Bytecode size:     4,968 bytes
Database CRC:      0x2d605f47
Stream state size: 20 bytes
Scratch size:      2,317 bytes
Compile time:      0.001 seconds
Peak heap usage:   9,732,096 bytes

Time spent scanning:       0.005 seconds
Corpus size:               6,701,044 bytes (3,280 blocks in 653 streams)
Matches per iteration:     653 (0.100 matches/kilobyte)
Overall block rate:        12,497,682.88 blocks/sec
Mean throughput (overall): 204,262.25 Mbit/sec
Max throughput (per core): 222,743.52 Mbit/sec

```
So why this pattern `4425:/[a-zA-Z]( |\x26)/sH` is bad performance with a simple other pattern `4402:/abcdefgh/sH` ? Or how to analyze this issue?

**Comment by fatchanghao** [comment]
Hello, first I suggest you turn off assertions in benchmarking by setting cmake option "-DDISABLE_ASSERTS=1".

For test3 and test4, the compiled results are almost the same, the only difference is '\x20' and '\x09' in literal matcher's table, when feeding them input data with no matches (like all null characters) they'll get exact the same performance. So what makes test3 slower than test4 is that whitespace is much more frequently appeared in your English corpus.

For test3 and test5, the compiled results are different, test3 contains a 8-byte literal while test5 only contains 2-byte literals. test3 uses an literal matcher which processes normal literals, while test5 uses the engine processing 2-byte short literal which is pretty fast.

You can use "hsdump" tool to check the compiled results, too.

**Comment by pengtianabc** [comment]
Thank you for your reply, i tried to analyze "hsdump" output, but i cant understand it, and also cant find some better offical document, is there any document or book can help to analyze it?

**Comment by fatchanghao** [comment]
> Thank you for your reply, i tried to analyze "hsdump" output, but i cant understand it, and also cant find some better offical document, is there any document or book can help to analyze it?

Maybe it's not easy to find document on this, but I think below files may help you understand the compiled results:
dump/rose_components.txt - the compiled DFA/NFA engine stats.
dump/rose_literals.txt - all literals information.
dump_lit_table_floating.txt - the selected literal matching algorithm details.

From these 3 files you can get most information you need.
