### ISSUE TITLE
[Bug] Scan fail for specify corpora and pattern in literal mode

### ISSUE THREAD

**Issue by pengtianabc** [intel/hyperscan#353]
Hi, everyone.
I try to use my custom corpora and simple pattern to benchmark by hsbench, it  will abort(RelWithDebug) or  scan fail(Release) in 
literal mode.
![image](https://user-images.githubusercontent.com/13852782/161196859-2c66420d-752a-46f2-afba-4f3a8c00b07a.png)

My pattern:
```
# will error
1:/xt>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD/i
# will error
# 1:/xt<DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD/i
2:/123/i
```

I have test in some case:

- In pattern id=1, either `>` or `<`, it will error.
- In pattern id=1, if i reduce the number of `D`, or replace the last `D` to `A`, it works ok.
- Without id=2, it works ok.
- In non-literal mode, it works ok.
-  In pattern id=1, replace `xt` to `xy`, it works ok

The error code is:
`src/rose/program_runtime.c +3492 `
In function: `roseRunProgram_l` 
![image](https://user-images.githubusercontent.com/13852782/161197239-75d00a5a-0fb4-45db-8a8d-8c58ef8f9603.png)

This is my corpora:
[23414.zip](https://github.com/intel/hyperscan/files/8394754/23414.zip)

I want to know why and how to fix it, really thanks for everyone first.

**Comment by danlark1** [comment]
Likely same as https://github.com/intel/hyperscan/issues/303
