### ISSUE TITLE
Does regular expressions support \0 substrings

### ISSUE THREAD

**Issue by wangfenggao** [intel/hyperscan#370]

**Comment by hongyang7** [comment]
Following 3 APIs deal with common regular expressions:
```hs_compile()```
```hs_compile_multi()```
```hs_compile_ext_multi()```
They regard \0 as an expression end (by using strlen()), so they don't support \0 as valid expression content.

Following 2 APIs deal with pure literal expressions:
```hs_compile_lit()```
```hs_compile_lit_multi()```
They support \0 as valid expression content, but user needs to provide expression length as new parameter.

**Comment by fatchanghao** [comment]
If you want to use '\0' in regular API, you should write "\x00" instead of zero-value character.
