### ISSUE TITLE
how to build it on windows 10?

### ISSUE THREAD

**Issue by loveJasmine** [intel/hyperscan#381]
i am blocked by:

Ragel state machine compiler not found hyperscan

PS C:\hyperscan\build> cmake -G “Visual Studio 16 2019” -D BOOST_ROOT=../boost_1_57_0/ -DBUILD_SHARED_LIBS=on/ ../
-- Build type RELWITHDEBINFO
-- using release build
-- Boost version: 1.78.0
-- Build date: 2022-12-05
CMake Error at CMakeLists.txt:101 (message):
  Ragel state machine compiler not found

**Comment by Kianqunki** [comment]
You can use Cygwin.
