### ISSUE TITLE
Pattern sets for hyperscan performance evaluation

### ISSUE THREAD

**Issue by ShaofengWu123** [intel/hyperscan#390]
Hi, I am testing hyperscan and comparing it with hardware regex accelerators recently. I checked the performance of hs in both [here](https://www.intel.com/content/www/us/en/collections/libraries/hyperscan/performance-analysis-hyperscan-hsbench.html) and [here](https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-hyperscan.html). However, I can not find the pattern sets, i.e. snort_pcre, snort_literals and teakettle 2500, on the internet. I tried installing snort3 and view the example rule set, but end up being confused about how snort_literals is obtained from its example rule set since it mentions nothing about the key word "literal". I wonder will these pattern sets be open-source ? Thanks.

**Comment by ShaofengWu123** [comment]
OK, after some efforts, I found the ruleset [here](https://01.org/sites/default/files/downloads/hyperscan/hsbench-samples.tar.bz2) . I found this link among all the issues and I think these ruleset and corpora should be put in a more obvious place so that people can get them with ease.

**Comment by hongyang7** [comment]
> OK, after some efforts, I found the ruleset [here](https://01.org/sites/default/files/downloads/hyperscan/hsbench-samples.tar.bz2) . I found this link among all the issues and I think these ruleset and corpora should be put in a more obvious place so that people can get them with ease.

Yes it's under our consideration, and perhaps with more ruleset to expose.

**Comment by akscs01** [comment]
> OK, after some efforts, I found the ruleset [here](https://01.org/sites/default/files/downloads/hyperscan/hsbench-samples.tar.bz2) . I found this link among all the issues and I think these ruleset and corpora should be put in a more obvious place so that people can get them with ease.

I Couldn't find it in the link mentioned above.. Could you point to correct or updated link for snort literal/pcres/teakettle if any ? Thanks in advance.

**Comment by ShaofengWu123** [comment]
> snort_pcre, snort_literals and teakettle 2500

Hi, it seems that this link has been redirected to somewhere else, and I do not have a valid link currently. Given the reply by authors, I think we need to wait for their updates.
