### ISSUE TITLE
Problem with deserialized database

### ISSUE THREAD

**Issue by Markoborodov** [intel/hyperscan#393]
Hi!

I use Hyperscan 5.4.0 on Linux x64 and Windows x64 systems. I want to compile an HS database on Windows, serialize it into binary file and then deserialize this file on Linux to scan data by this database. But I get an error when I scan data by this deserialized database on Linux:
```
malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```
Stack trace:
```
==2669817== Process terminating with default action of signal 11 (SIGSEGV)
==2669817==  General Protection Fault
==2669817==    at 0x6B5B9A: runSheng
==2669817==    by 0x6B37BA: avx2_nfaQueueExecToMatch
==2669817==    by 0x6C092B: avx2_blockInitSufPQ
==2669817==    by 0x6BD103: avx2_roseBlockExec
==2669817==    by 0x6A0847: avx2_hs_scan
```
Valgrind also shows an error:
```
==2669817== Invalid write of size 8
==2669817==    at 0x880261: avx2_nfaExecMpv_initCompressedState
==2669817==    by 0x6C376E: avx2_roseInitState
==2669817==    by 0x6A0AD2: avx2_hs_open_stream
```

In addition, sizes of the same serialized database on Linux and Windows are different. In both cases, hardware optimization during compilation (hs_compile_ext_multi) was disabled.

What could be the reason? Is serialized database portable between different systems/platforms?

**Comment by hongyang7** [comment]
It's not suggested that (de)serialization are done across Linux and Windows platforms.
At least one issue exists that data type **_long_** has different sizes on these 2 platforms: Linux uses LP64 model (64-bit for long), while Windows uses LLP64 model (32-bit for long).
