### ISSUE TITLE
Why is Hyperscan not support fat runtime on Windows platforms？

### ISSUE THREAD

**Issue by Stevenkop** [intel/hyperscan#408]
Why is "fat runtime" not supported on Windows? Is it due to technical reasons or lack of adaptation work? If I need to use it on Windows, what tasks do I need to perform?

**Comment by Stevenkop** [comment]
Seems like it's due to ifunc, is there a way to achieve a smooth migration? Is it possible to use fat runtime on Windows?

**Comment by hongyang7** [comment]
The fat runtime feature is only available on Linux.
You might config the target arch directly on Windows (http://intel.github.io/hyperscan/dev-reference/getting_started.html#target-architecture). Not smooth, but can work.

**Comment by Stevenkop** [comment]
Okay, I hope it can still achieve cross-platform compatibility on Windows as well.
