### ISSUE TITLE
encountering problems of "multiple definition of XXX"   when compiling hyperscan in centos with x86_64

### ISSUE THREAD

**Issue by zrpkid** [intel/hyperscan#422]
When I compile hyperscan  5.4.1, I encountered the following problems, I don't know how to solve it, can someone give me some suggestions?
![1](https://github.com/intel/hyperscan/assets/32765084/c1af4a96-5fd2-4c7d-a50c-6a7efb533464)

**Comment by gliwka** [comment]
Which version of Centos and GCC are you using? Do you have a devtoolset in use?
