### ISSUE TITLE
Compiled database backward/forward compatibility

### ISSUE THREAD

**Issue by ptoomey3** [intel/hyperscan#71]
I was writing a test that runs in Ci and wanted to checkin a statically compiled DB exclusively for testing. My local machine compiled the DB using HS 4.6, and the CI server was on HS 4.4. I noticed that I was unable to load the DB. In the end this wasn't super surprising, but it got me thinking about whether there is any expectation for forward/backward compatibility of compiled databases between versions. For example, can one assume compatibility between minor releases (such as 4.4.1 vs. 4.4.2)?

**Comment by ptoomey3** [comment]
I think I answered my own question. I was trying to hunt down your documentation, but it looks like something changed and your GitHub Pages site no longer loads: blah. But, I did find what I was looking for in https://github.com/intel/hyperscan/blob/5fafad2dfb50bf7edb9ef1bfd7671962bb85279d/dev-reference/serialization.html#L80-L85. So, it seems like one needs to ensure that whatever version of the library compiles the DB/serializes it, is also the same version that deserializes it.

**Comment by mdb256** [comment]
That's correct - we do require that the DB is compiled with the same version of the library for serialization and deserialization. This is to avoid having to make version checks for things at runtime, which might impact performance. We try to ensure that compiling patterns is fast enough that having to rebuild DBs isn't a significant factor when upgrading HS versions.

Also: yes, the project moved from github.com/01org to github.com/intel - so the GH Pages site is now: http://intel.github.io/hyperscan/dev-reference/

I had updated the link on the front page/README.md, and links to/clones of the old repo name will redirect to the new one, but for reasons outside of my control we couldn't get a redirect for the GitHub Pages.
