### ISSUE TITLE
Is there any meaningful performance penalty for duplicate patterns?

### ISSUE THREAD

**Issue by ptoomey3** [intel/hyperscan#72]
I was going to pull together an actual benchmark to test this, but I thought I'd start by going straight to the source to get a sense of how you folks expect this to work. Let's say I have 100 unique patterns that I compile into a DB. If I add a another pattern, and it just so happens to have the same pattern as one of the existing patterns, do you pay any meaningful performance penalty? You would obviously get an extra callback invocation since you would be matching two different pattern IDs. But, I'm curious if there is anything beyond that? We have a use case where we might, over time, have two patterns that are identical, and it would be nice to let them each retain a unique ID. But, if there is a meaningful performance penalty, we could arrange things such that a single pattern is used.

**Comment by mdb256** [comment]
That's correct - you will get repeated callback hits if the pattern matches, but there should not be any other performance impacts.

**Comment by ptoomey3** [comment]
Thanks so much for the quick reply!
