### ISSUE TITLE
`hs_reset_and_expand_stream` crashed when reset on a closed stream

### ISSUE THREAD

**Issue by flier** [intel/hyperscan#73]
I believe it could return `HS_INVALID` or other error instead of crash 
> hyperscan-92e4b75ad5e993df(22216,0x70000467c000) malloc: *** error for object 0x7fef8fd01b00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by mdb256** [comment]
If you have called `hs_close_stream()` the `hs_stream_t` object will be freed and then invalid for use. We don't quite understand why you are seeing an error from `free()` - `hs_reset_and_expand_stream` should not be calling `free()`.

We will update our documentation for `hs_close_stream` - this wasn't explicitly described.

**Comment by flier** [comment]
It's fair, there is a little confusion between `open/close` and `open/reset`, the `close` should be `free`, right?

**Comment by mdb256** [comment]
We improved the documentation for `hs_close_stream()` in v4.7.0.
