### ISSUE TITLE
PREFILTER pattern fails to match

### ISSUE THREAD

**Issue by eliaslevy** [intel/hyperscan#74]
I go the following pattern (`(Здра).*уйте/\1`) that I am compiling with `SINGLEMATCH`, `UTF8`, and `PREFILTER`, and which I am attempting to match to `ЗДРАВСТВУЙТЕ/ЗДРА` without success.

Other patterns using back references and `PREFILTER` seem to work.

**Comment by mdb256** [comment]
Are you also using `HS_FLAG_CASELESS`? That appears to be a lower case pattern and upper case data.

I get a match from a quick test if I add caseless.

**Comment by eliaslevy** [comment]
Yes, apologies.  Using `CASELESS` as well.

**Comment by mdb256** [comment]
Maybe I am missing something, but to replicate the issue I have edited examples/simplegrep.c and change the `hs_compile()` argument `HS_FLAG_DOTALL` to those above, like:
```diff
--- a/examples/simplegrep.c
+++ b/examples/simplegrep.c
@@ -160,7 +160,7 @@ int main(int argc, char *argv[]) {
      */
     hs_database_t *database;
     hs_compile_error_t *compile_err;
-    if (hs_compile(pattern, HS_FLAG_DOTALL, HS_MODE_BLOCK, NULL, &database,
+    if (hs_compile(pattern, HS_FLAG_UTF8|HS_FLAG_CASELESS|HS_FLAG_PREFILTER|HS_FLAG_SINGLEMATCH, HS_MODE_BLOCK, NULL, &database,
                    &compile_err) != HS_SUCCESS) {
```
And then put the match data in a file `input.txt`:
```
$ head input.txt
ЗДРАВСТВУЙТЕ/ЗДРА
```
Then:
```
$ bin/simplegrep '(Здра).*уйте/\1' input.txt
Scanning 34 bytes with Hyperscan
Match for pattern "(Здра).*уйте/\1" at offset 25
```
So it seems to work for me.

Hyperscan doesn't support matching with back references, but does returning the match at the `/` char, because of `PREFILTER`.

**Comment by eliaslevy** [comment]
I verified you are correct by patching `simplegrep` the same way.  That said, the pattern still fails on my code.  I am using the Java bindings for the library ([cerebuild/hyperscan-java](https://github.com/cerebuild/hyperscan-java)), so the error may be in translating the pattern or string to match from Java to hyperscan.  I'll take a look.

**Comment by gliwka** [comment]
@eliaslevy Did you find anything?

**Comment by eliaslevy** [comment]
User error. Sorry for the noise.
