### ISSUE TITLE
bindings to other languages

### ISSUE THREAD

**Issue by Announcement** [intel/hyperscan#76]
would it be appropriate and reasonable to ask for node.js bindings, if so i would like to provide such inquiry as it would be greatly appreciated to supplement current limiting regular expression engine implementations in javascript.

**Comment by mdb256** [comment]
We currently do not provide bindings for languages other than C.

There are third party efforts to provide bindings for Hyperscan to other languages such as Javascript.

**Comment by aidenwallis** [comment]
@mdb256 Does a Javascript based binding exist yet? If so, you got a link to point me to the repo?

Cheers.
