### ISSUE TITLE
Debug build breaks because of -Werror switched on

### ISSUE THREAD

**Issue by patrickfrey** [intel/hyperscan#77]
hyperscan CMakeLists.txt:
 if (NOT RELEASE_BUILD)
        # -Werror is most useful during development, don't potentially break
        # release builds
        set(EXTRA_C_FLAGS "${EXTRA_C_FLAGS} -Werror")
        set(EXTRA_CXX_FLAGS "${EXTRA_CXX_FLAGS} -Werror")
    endif()

Compiler gcc (-std=c99), platform Ubuntu 14.04 

The flag -Werror breaks the build because of the following warning that remains a warning if -Werror is not turned on.
    warning: ISO C99 requires rest arguments to be used [enabled by default]
         DEBUG_PRINTF("...")

**Comment by mdb256** [comment]
This is a little confusing. We perform gcc builds on Ubuntu 14.04 regularly and have not seen this warning. Hyperscan uses `-std=c99` by default. Have you enabled more warnings via `CFLAGS`?

As an aside: a debug build enables assertions which affect performance, so is typically only used when modifying Hyperscan code. If you just need debugging symbols, these are generated with the `RelWithDebInfo` CMake config.

**Comment by patrickfrey** [comment]
Yes it was my fault. I am building hyperscan as submodule and a -pedantic crept in inherited from my main Makefile. Didn't see that. Sorry!
