### ISSUE TITLE
strange crash when scan vector in golang/cgo

### ISSUE THREAD

**Issue by flier** [intel/hyperscan#83]
Hi, I'm maintain [a golang binding](https://github.com/flier/gohs) for hyperscan, there is [a strange crash issue](https://github.com/flier/gohs/issues/8) was reported, which can be reproduced after thousands of scan vector calls.

This [stack trace](https://gist.github.com/vgalu/5dc2837a75403a42388f5fdd8610eefe) comes from running [this test program](https://gist.github.com/vgalu/6fcabee7c4c954ec9c8a70a6a7f5b0ee).

It seems some memory was corrupt, are there any pointer will be saved in the compile and scan phases? Because golang use a GC to manage all the memory, the GO pointer passed to hyperscan can't be saved after call.

Besides, I also tried to lock the scanning goroutine to its current thread with `runtime. LockOSThread `, but it seems no effects.

Thanks

**Comment by vgalu** [comment]
The data pointer is stored in the scratch in [populateCoreInfo() via hs_scan_stream_internal() via hs_scan_vector()](https://github.com/intel/hyperscan/blob/master/src/runtime.c#L120) and then used in [hwlmExecStreaming()](https://github.com/intel/hyperscan/blob/3dcd51c272bb6be2b256064548570ad8bd3b40f1/src/hwlm/hwlm.c#L201)

**Comment by flier** [comment]
We found it caused by Golang aggressive GC strategy.
