### ISSUE TITLE
hs_compile_ext_multi is very slow

### ISSUE THREAD

**Issue by idogoshen** [intel/hyperscan#84]
Hi,

I was trying to move from hs_compile_multi to hs_compile_ext_multi in our project in order to control the offsets of interest per expression

Compiling the same list of expressions is way slower with the extended parameters then w/o.
can be **100x** slower!

e.g. w/o ext
[10K_urls-id.txt](https://github.com/intel/hyperscan/files/1726827/10K_urls-id.txt)
> cgs@ubuntu:~/VMShare/HYPERSCAN$ Release/bin/hsbench -N -e ~/VMShare/url/10K_urls-id.txt -c corpus/web.db 
Signatures:        /home/cgs/VMShare/url/10K_urls-id.txt
Hyperscan info:    Version: 4.6.0 Features: AVX2 Mode: BLOCK
Expression count:  9,435
Bytecode size:     1,113,768 bytes
Database CRC:      0x761aebb6
Scratch size:      4,042 bytes
Compile time:     **0.420 seconds**
Peak heap usage:   78,446,592 bytes

vs. with ext
[10K_urls-id-ext.txt](https://github.com/intel/hyperscan/files/1726828/10K_urls-id-ext.txt)
> cgs@ubuntu:~/VMShare/HYPERSCAN$ Release/bin/hsbench -N -e ~/VMShare/url/10K_urls-id-ext.txt -c corpus/web.db 
Signatures:        /home/cgs/VMShare/url/10K_urls-id-ext.txt
Hyperscan info:    Version: 4.6.0 Features: AVX2 Mode: BLOCK
Expression count:  9,435
Bytecode size:     3,635,216 bytes
Database CRC:      0xa2360594
Scratch size:      777,574 bytes
Compile time:      **71.189 seconds**
Peak heap usage:   967,745,536 bytes

Does it make sense (i.e. expected behavior)?  a bug? or I'm just doing something wrong?

Thanx,
- Ido

**Comment by jviiret** [comment]
Hi Ido,

70+ sec is pretty slow, but this is not surprising behavior. Your first case consists entirely of literal patterns, and Hyperscan has a shortcut to handle those -- essentially, we can avoid transforming them into NFA graphs and doing a lot of pattern analysis on them, and just push them straight into our literal matcher.

Once you add extended parameters, this shortcut is no longer used. We do the equivalent of this transformation for these cases:

    IN:  /foobar\.com/H{min_offset=0,max_offset=256}
    OUT: /^.{0,246}foobar\.com/sH

These patterns go through all our normal analysis and optimization passes, and there's a lot more overhead during compilation there. There may be improvements we can make to this in future releases.

For now, if you need to constrain your matches for all your patterns to the first 256 bytes and you're scanning in block mode, have you considered only passing the first 256 bytes of your data to `hs_scan()`?

**Comment by idogoshen** [comment]
Hi jviret

Thanx for the detailed response, it sure explains and clears my doubts.
I guess this somehow fulls under the [prefer-literals performance tip](http://intel.github.io/hyperscan/dev-reference/performance.html#prefer-literals) (though it doesn't refer directly to compile time)

Unfortunately in our general use case we do have non-literal regex that may be in different offsets/lengths, but I'll do try to check and optimize for that special case as you suggest.

Thanx,
 Ido
