### ISSUE TITLE
hsbench AVX512 support

### ISSUE THREAD

**Issue by idogoshen** [intel/hyperscan#87]
Hi,

I have very new [Intel-Xeon-6154 skylake](https://ark.intel.com/products/120495/Intel-Xeon-Gold-6154-Processor-24_75M-Cache-3_00-GHz) server 

HS is forcefully compiled for skylake-avx512 with
`cmake -DBOOST_ROOT=/home/cgs/boost_1_60_0 /home/cgs/HS/hyperscan-4.6.0/ -DCMAKE_C_FLAGS="-march=skylake-avx512" -DCMAKE_CXX_FLAGS="-march=skylake-avx512" -DBUILD_AVX512=on
`

running hsbench it still say AVX2
`Hyperscan info:    Version: 4.6.0 Features: AVX2 Mode: BLOCK`

had to patch with [hsbench.patch.txt](https://github.com/intel/hyperscan/files/1859577/hsbench.patch.txt)

To make it work with AVX512
`Hyperscan info:    Version: 4.6.0 Features: AVX512 Mode: BLOCK`

Thanx,
- Ido

**Comment by xiangwang1** [comment]
Hi Ido,

Thanks for the report. We can't reproduce this issue on our Skylake machine.
I don't think it's necessary to add `hs_populate_platform(&platform);` before `hs_compile_ext_multi()` as we'll check platform info at: https://github.com/intel/hyperscan/blob/7dfaca66355e53de5c4f38602420b13a6af45206/src/hs.cpp#L229
and print database info at: 
https://github.com/intel/hyperscan/blob/7dfaca66355e53de5c4f38602420b13a6af45206/src/database.c#L443

Could you help check the above code in your case?

Xiang

**Comment by idogoshen** [comment]
Oops... my mistake, 
@xiangwang1 you are right - it does automatically detect AVX512, no need to provide platform.
(I guess I mixed with my non AVX512 builds) 
sorry  :-&
