### ISSUE TITLE
"Unrecognized flag"

### ISSUE THREAD

**Issue by DesWurstes** [intel/hyperscan#88]
The code:

```c
...
unsigned int params = HS_FLAG_SINGLEMATCH | HS_FLAG_PREFILTER \
		| HS_FLAG_CASELESS | HS_FLAG_DOTALL;
hs_compile_multi(something, &params, something, something, something,
		NULL, something, compile_error);
```

Compile_error->message says "Unrecognized flag"

If I replace the declaration of `params` with `unsigned int params = 0;` It still gives the same error.

If I remove `hs_compile_multi` and add `hs_compile` (also remove the `&`) it compiles successfully.

Even worse, if the code is

```
hs_compile_multi(something, &params, something, number_of_patterns, something,
		NULL, something, compile_error);
```

It works iff `number_of_patterns` is `1` or `2`. If it's larger than those, it throws "Unrecognized flag".

**Comment by kururu-abdo** [comment]
how to resolve this:
Unrecognized flags: enable_vm_service:49817
Could not find a command named "get".
Run "pub help" to see available commands.
Process finished with exit code 64

**Comment by xiangwang1** [comment]
We don't think this is an internal error from Hyperscan. Can you double check with your environment setup?
