### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by wso4133560** [intel/hyperscan#89]
int flag = hs_compile("GET|POST", HS_FLAG_SOM_LEFTMOST,
				HS_MODE_BLOCK, nullptr, &m_database, &compile_err);

flag = -4;
this case occur internal error in 4.6.0，now i will test 4.7.0。

**Comment by xiangwang1** [comment]
Can you show a more complete example that includes variable declarations?

**Comment by wso4133560** [comment]
sorry，I don't konw more about it. I use diffrent flag to avoid this error.

**Comment by xiangwang1** [comment]
I can't reproduce your error. Can you provide the full source file so we can have a look at?

**Comment by wso4133560** [comment]
This error occur in windows, not occur in Linux.I trace the code,finally i find the error occur in ng_cal_componets.cpp:354.
NFAVertex v = new2old.at(uv); this code throw exception
Different complie has different way in stl.
![default](https://user-images.githubusercontent.com/6397344/38713996-a7e3a52c-3f06-11e8-91ae-98c40a617404.png)

**Comment by aming2007** [comment]
Hi, I got the same problem as wso4133560.
ng_cal_componets.cpp:354.

NFAVertex v = new2old.at(uv); 

	const mapped_type& at(const key_type& _Keyval) const
		{	// find element matching _Keyval
		const_iterator _Where = _Mybase::lower_bound(_Keyval);
		if (_Where == _Mybase::end())
			_Xout_of_range("invalid unordered_map<K, T> key");

this code throw exception

**Comment by aming2007** [comment]
My environment as flow：
1. win10
2. VS2017 15.4.3
3. Hyperscan V4.7.0
4. Cmake 3.11.1
5. ragel 6.10

**Comment by aming2007** [comment]
Hi, I encountered the same problem as wso4133560, when i tested debug_x64 unit-hyperscan.exe(Release version is ok). 

[ RUN      ] HyperscanTestBehaviour.CloseStreamAfterTermination
4.7.0\unit\hyperscan\behaviour.cpp(943): error: Value of: db != nullptr
  Actual: false
Expected: true

ng_cal_componets.cpp:354.

NFAVertex v = new2old.at(uv);

const mapped_type& at(const key_type& _Keyval) const
	{	// find element matching _Keyval
	const_iterator _Where = _Mybase::lower_bound(_Keyval);
	if (_Where == _Mybase::end())
		_Xout_of_range("invalid unordered_map<K, T> key");
this code throw exception
--------------------
My environment as flow：
1. win10
2. VS2017 15.4.3
3. Hyperscan V4.7.0
4. Cmake 3.11.1
5. ragel 6.10

**Comment by luchy0120** [comment]
@wso4133560 , @aming2007 , we will change the implementation in the next release . For now , I 've  
found the cause and you can download the zip below to fixes the issue. I changed the method in ng_undirected.h  to use share_ptr to avoid copying NFAUndirectedGraph . Thus, the exception won't 
be thrown by "at()". 
[update.zip](https://github.com/intel/hyperscan/files/2038047/update.zip)

**Comment by luchy0120** [comment]
@wso4133560 , @aming2007 , we will change these implementation in the next release . Fow now , I've
found the cause and fixed the issue . I changed the method in ng_undirected.h to return share_ptr to avoid 
copying . Thus , exception won't be thrown by "at()".
[update.zip](https://github.com/intel/hyperscan/files/2038087/update.zip)

**Comment by xiangwang1** [comment]
Close as this issue has been fixed.
