### ISSUE TITLE
libpcre dependency is pinned

### ISSUE THREAD

**Issue by rhaist** [intel/hyperscan#92]
Building hyperscan and the corresponding tools currently requires libpcre with an exact version of  8.41:

```
-- Checking for module 'libpcre=8.41'
--   
-- PCRE version 8.41 not found
-- PCRE 8.41 not found
-- PCRE 8.41 not found, not building hscollider
```

If possible, please avoid using pinned versions as dependencies, because this makes packaging hyperscan and the tools harder for package maintainers like me.

**Comment by JamiesZhang** [comment]
Excuse me, I meet the same problem, but I already download libpcre 8.41, why it still alert the error? How did you solve it?

**Comment by xiangwang1** [comment]
Thanks. PCRE version >= 8.41 is now accepted by Hyperscan.
